import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {useEffect,useState} from 'react';
import {ActivityIndicator,Pressable,StyleSheet,Switch,Text,View} from 'react-native';
import {Button,Page,Screen} from '../../src/components';
import {useAuthStore} from '../../src/auth';
import {isSupabaseConfigured} from '../../src/supabase';
import {requestNotificationPermission,rescheduleMealNotifications} from '../../src/notifications';
import {useAppStore} from '../../src/store';
import {colors} from '../../src/theme';

function ProviderLinkButton({provider,disabled,onMessage}:{provider:'google';disabled:boolean;onMessage:(message:string)=>void}){
 const linkProvider=useAuthStore(state=>state.linkProvider),[busy,setBusy]=useState(false);
 const run=async()=>{setBusy(true);onMessage('');try{const linked=await linkProvider(provider);onMessage(linked?'Đã liên kết tài khoản Google.':'Bạn đã hủy liên kết Google. Dữ liệu vẫn được giữ nguyên.')}catch(reason){onMessage(reason instanceof Error?reason.message:'Không thể liên kết Google.')}finally{setBusy(false)}};
 return <Pressable accessibilityRole="button" accessibilityLabel="Liên kết với Google" disabled={disabled||busy} onPress={()=>void run()} style={[x.provider,disabled?x.disabled:undefined]}><Ionicons name="logo-google" size={22} color="#DB4437"/><Text style={x.providerText}>{busy?'Đang mở Google...':'Liên kết với Google'}</Text>{busy?<ActivityIndicator size="small"/>:null}</Pressable>;
}

export default function Settings(){
 const status=useAuthStore(state=>state.status),installationId=useAuthStore(state=>state.installationId),devices=useAuthStore(state=>state.devices),error=useAuthStore(state=>state.error),initialize=useAuthStore(state=>state.initialize),loadDevices=useAuthStore(state=>state.loadDevices),revokeDevice=useAuthStore(state=>state.revokeDevice),logout=useAuthStore(state=>state.logout);
 const [message,setMessage]=useState<string>(),[busy,setBusy]=useState<'logout'>();
 const notificationsEnabled=useAppStore(state=>state.notificationsEnabled),preparationMinutes=useAppStore(state=>state.preparationReminderMinutes),setNotificationPreferences=useAppStore(state=>state.setNotificationPreferences),plans=useAppStore(state=>state.weeklyPlans);
 useEffect(()=>{if(status==='registered')void loadDevices()},[loadDevices,status]);
 const apiConfigured=isSupabaseConfigured,linked=status==='registered';
 const changeNotifications=async(enabled:boolean)=>{if(enabled&&!await requestNotificationPermission()){setMessage('Bạn chưa cấp quyền thông báo. Có thể bật lại trong Cài đặt hệ thống.');return}setNotificationPreferences(enabled);await rescheduleMealNotifications(plans,enabled,preparationMinutes);setMessage(enabled?'Đã bật nhắc chuẩn bị và nấu ăn.':'Đã tắt nhắc bữa ăn.')};
 const changePreparation=(minutes:number)=>{setNotificationPreferences(notificationsEnabled,minutes);void rescheduleMealNotifications(plans,notificationsEnabled,minutes)};
 return <Screen><Page><View style={x.header}><Pressable accessibilityRole="button" accessibilityLabel="Quay lại" onPress={()=>router.back()} style={x.back}><Ionicons name="arrow-back" size={22}/></Pressable><View><Text style={x.title}>Cài đặt</Text><Text style={x.subtitle}>Tài khoản và thiết bị</Text></View></View>
  <View style={x.accountCard}><View style={[x.accountIcon,linked&&x.linkedIcon]}><Ionicons name={linked?'checkmark-circle':'phone-portrait-outline'} size={28} color={linked?'#fff':colors.primaryDark}/></View><View style={x.accountCopy}><Text style={x.sectionTitle}>{linked?'Đã liên kết tài khoản':'Đang dùng với tư cách khách'}</Text><Text style={x.subtitle}>{linked?'Dữ liệu có thể được sử dụng trên nhiều thiết bị.':'Dữ liệu hiện gắn với lần cài đặt trên thiết bị này.'}</Text><Text style={x.installation} numberOfLines={1}>ID: {installationId??'Đang khởi tạo...'}</Text></View></View>
  {!apiConfigured?<View style={x.notice}><Ionicons name="cloud-offline-outline" size={21} color={colors.secondary}/><View style={x.accountCopy}><Text style={x.noticeTitle}>Supabase chưa được kết nối</Text><Text style={x.subtitle}>Thêm EXPO_PUBLIC_SUPABASE_URL và EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY để bật đồng bộ cloud.</Text></View></View>:null}
  {!linked?<View style={x.card}><Text style={x.sectionTitle}>Dùng trên nhiều thiết bị</Text><Text style={x.subtitle}>Liên kết Google sẽ nâng cấp tài khoản khách hiện tại. ID người dùng, gia đình, kế hoạch và danh sách mua sắm được giữ nguyên.</Text><ProviderLinkButton provider="google" disabled={!apiConfigured||Boolean(busy)} onMessage={setMessage}/><Text style={x.helpText}>Daily Meals không nhận mật khẩu Google của bạn.</Text></View>:null}
  {message?<Text style={x.message}>{message}</Text>:null}{error?<View style={x.errorBox}><Text style={x.errorText}>{error}</Text><Button title="Thử kết nối lại" onPress={()=>void initialize()}/></View>:null}
  {linked?<View style={x.card}><View style={x.rowBetween}><Text style={x.sectionTitle}>Thiết bị đã đăng nhập</Text><Pressable accessibilityRole="button" accessibilityLabel="Làm mới danh sách thiết bị" onPress={()=>void loadDevices()}><Ionicons name="refresh" size={21} color={colors.primaryDark}/></Pressable></View>{devices.map(device=><View key={device.id} style={x.device}><Ionicons name={device.platform==='ios'?'logo-apple':device.platform==='android'?'logo-android':'desktop-outline'} size={22}/><View style={x.accountCopy}><Text style={x.deviceName}>{device.deviceName??'Thiết bị Daily Meals'}{device.current?' · Hiện tại':''}</Text><Text style={x.subtitle}>Hoạt động {new Date(device.lastSeenAt).toLocaleDateString('vi-VN')}</Text></View>{!device.current?<Pressable accessibilityRole="button" accessibilityLabel={`Thu hồi ${device.deviceName??'thiết bị'}`} onPress={()=>void revokeDevice(device.id)} style={x.revoke}><Text style={x.revokeText}>Thu hồi</Text></Pressable>:null}</View>)}</View>:null}
  <View style={x.card}><View style={x.rowBetween}><View style={x.accountCopy}><Text style={x.sectionTitle}>Nhắc chuẩn bị bữa ăn</Text><Text style={x.subtitle}>Nhận thông báo trước giờ chuẩn bị và khi đến giờ nấu.</Text></View><Switch accessibilityLabel="Bật nhắc chuẩn bị bữa ăn" value={notificationsEnabled} onValueChange={value=>void changeNotifications(value)} trackColor={{false:'#D8D4CB',true:'#A8D69A'}} thumbColor={notificationsEnabled?colors.primary:'#fff'}/></View>{notificationsEnabled?<><Text style={x.optionLabel}>Nhắc trước giờ nấu</Text><View style={x.reminderOptions}>{[15,30,45,60].map(minutes=><Pressable key={minutes} accessibilityRole="radio" accessibilityState={{selected:preparationMinutes===minutes}} accessibilityLabel={`Nhắc trước ${minutes} phút`} onPress={()=>changePreparation(minutes)} style={[x.reminderOption,preparationMinutes===minutes&&x.reminderActive]}><Text style={[x.reminderText,preparationMinutes===minutes&&x.reminderTextActive]}>{minutes} phút</Text></Pressable>)}</View></>:null}</View>
  <View style={x.card}><Text style={x.sectionTitle}>Quyền riêng tư</Text><Text style={x.subtitle}>Daily Meals không sử dụng IMEI hoặc mã phần cứng. Phiên đăng nhập được Supabase Auth mã hóa và lưu cục bộ trên thiết bị.</Text>{apiConfigured?<Button title={busy==='logout'?'Đang đăng xuất...':'Đăng xuất trên thiết bị này'} outline onPress={()=>{setBusy('logout');void logout().finally(()=>setBusy(undefined))}}/>:null}</View>
 </Page></Screen>;
}
const x=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:8},back:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontSize:25,fontWeight:'800',color:colors.primaryDark},subtitle:{fontSize:12,color:colors.muted,lineHeight:18,marginTop:3},accountCard:{backgroundColor:colors.soft,borderRadius:18,padding:16,flexDirection:'row',gap:12,alignItems:'center'},accountIcon:{width:52,height:52,borderRadius:26,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},linkedIcon:{backgroundColor:colors.primary},accountCopy:{flex:1},sectionTitle:{fontSize:17,fontWeight:'800'},installation:{fontSize:10,color:colors.muted,marginTop:6},notice:{backgroundColor:'#FFF5E3',padding:14,borderRadius:14,flexDirection:'row',gap:10},noticeTitle:{fontWeight:'800',color:'#A85D00'},card:{backgroundColor:'#fff',borderRadius:17,padding:16,gap:13,borderWidth:1,borderColor:colors.border},provider:{minHeight:52,borderWidth:1,borderColor:colors.border,borderRadius:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},providerText:{fontWeight:'700'},helpText:{fontSize:11,color:colors.muted,textAlign:'center'},disabled:{opacity:.45},message:{backgroundColor:colors.soft,color:colors.primaryDark,padding:12,borderRadius:12,fontWeight:'700'},errorBox:{backgroundColor:'#FFF0ED',padding:14,borderRadius:14,gap:10},errorText:{color:colors.danger},rowBetween:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},optionLabel:{fontSize:12,fontWeight:'800',color:colors.muted},reminderOptions:{flexDirection:'row',gap:7},reminderOption:{flex:1,minHeight:44,borderWidth:1,borderColor:colors.border,borderRadius:12,alignItems:'center',justifyContent:'center'},reminderActive:{backgroundColor:colors.primary,borderColor:colors.primary},reminderText:{fontSize:12,fontWeight:'700'},reminderTextActive:{color:'#fff'},device:{minHeight:62,flexDirection:'row',gap:10,alignItems:'center',borderTopWidth:1,borderColor:colors.border,paddingTop:10},deviceName:{fontWeight:'700'},revoke:{minHeight:44,justifyContent:'center',paddingHorizontal:8},revokeText:{color:colors.danger,fontWeight:'700'}});
