import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {useEffect,useState} from 'react';
import {ActivityIndicator,Pressable,StyleSheet,Text,View} from 'react-native';
import {Button,Page,Screen} from '../../src/components';
import {useAuthStore} from '../../src/auth';
import {isSupabaseConfigured} from '../../src/supabase';
import {colors} from '../../src/theme';

function ProviderLinkButton({provider,disabled,onMessage}:{provider:'google'|'apple';disabled:boolean;onMessage:(message:string)=>void}){
 const linkProvider=useAuthStore(state=>state.linkProvider),[busy,setBusy]=useState(false);
 const label=provider==='google'?'Google':'Apple';
 const run=async()=>{setBusy(true);try{await linkProvider(provider);onMessage(`Đã liên kết tài khoản ${label}.`)}catch(reason){onMessage(reason instanceof Error?reason.message:`Không thể liên kết ${label}.`)}finally{setBusy(false)}};
 return <Pressable accessibilityRole="button" disabled={disabled||busy} onPress={()=>void run()} style={[x.provider,disabled?x.disabled:undefined]}><Ionicons name={provider==='google'?'logo-google':'logo-apple'} size={22} color={provider==='google'?'#DB4437':'#111'}/><Text style={x.providerText}>Liên kết với {label}</Text>{busy?<ActivityIndicator size="small"/>:null}</Pressable>;
}

export default function Settings(){
 const status=useAuthStore(state=>state.status),installationId=useAuthStore(state=>state.installationId),devices=useAuthStore(state=>state.devices),error=useAuthStore(state=>state.error),initialize=useAuthStore(state=>state.initialize),loadDevices=useAuthStore(state=>state.loadDevices),revokeDevice=useAuthStore(state=>state.revokeDevice),logout=useAuthStore(state=>state.logout);
 const [message,setMessage]=useState<string>(),[busy,setBusy]=useState<'logout'>();
 useEffect(()=>{if(status==='registered')void loadDevices()},[loadDevices,status]);
 const apiConfigured=isSupabaseConfigured,linked=status==='registered';
 return <Screen><Page><View style={x.header}><Pressable accessibilityRole="button" accessibilityLabel="Quay lại" onPress={()=>router.back()} style={x.back}><Ionicons name="arrow-back" size={22}/></Pressable><View><Text style={x.title}>Cài đặt</Text><Text style={x.subtitle}>Tài khoản và thiết bị</Text></View></View>
  <View style={x.accountCard}><View style={[x.accountIcon,linked&&x.linkedIcon]}><Ionicons name={linked?'checkmark-circle':'phone-portrait-outline'} size={28} color={linked?'#fff':colors.primaryDark}/></View><View style={x.accountCopy}><Text style={x.sectionTitle}>{linked?'Đã liên kết tài khoản':'Đang dùng với tư cách khách'}</Text><Text style={x.subtitle}>{linked?'Dữ liệu có thể được sử dụng trên nhiều thiết bị.':'Dữ liệu hiện gắn với lần cài đặt trên thiết bị này.'}</Text><Text style={x.installation} numberOfLines={1}>ID: {installationId??'Đang khởi tạo...'}</Text></View></View>
  {!apiConfigured?<View style={x.notice}><Ionicons name="cloud-offline-outline" size={21} color={colors.secondary}/><View style={x.accountCopy}><Text style={x.noticeTitle}>Supabase chưa được kết nối</Text><Text style={x.subtitle}>Thêm EXPO_PUBLIC_SUPABASE_URL và EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY để bật đồng bộ cloud.</Text></View></View>:null}
  {!linked?<View style={x.card}><Text style={x.sectionTitle}>Dùng trên nhiều thiết bị</Text><Text style={x.subtitle}>Liên kết tài khoản sẽ giữ nguyên user ẩn danh và toàn bộ dữ liệu hiện tại.</Text><ProviderLinkButton provider="google" disabled={!apiConfigured||Boolean(busy)} onMessage={setMessage}/><ProviderLinkButton provider="apple" disabled={!apiConfigured||Boolean(busy)} onMessage={setMessage}/></View>:null}
  {message?<Text style={x.message}>{message}</Text>:null}{error?<View style={x.errorBox}><Text style={x.errorText}>{error}</Text><Button title="Thử kết nối lại" onPress={()=>void initialize()}/></View>:null}
  {linked?<View style={x.card}><View style={x.rowBetween}><Text style={x.sectionTitle}>Thiết bị đã đăng nhập</Text><Pressable accessibilityRole="button" accessibilityLabel="Làm mới danh sách thiết bị" onPress={()=>void loadDevices()}><Ionicons name="refresh" size={21} color={colors.primaryDark}/></Pressable></View>{devices.map(device=><View key={device.id} style={x.device}><Ionicons name={device.platform==='ios'?'logo-apple':device.platform==='android'?'logo-android':'desktop-outline'} size={22}/><View style={x.accountCopy}><Text style={x.deviceName}>{device.deviceName??'Thiết bị Daily Meals'}{device.current?' · Hiện tại':''}</Text><Text style={x.subtitle}>Hoạt động {new Date(device.lastSeenAt).toLocaleDateString('vi-VN')}</Text></View>{!device.current?<Pressable accessibilityRole="button" accessibilityLabel={`Thu hồi ${device.deviceName??'thiết bị'}`} onPress={()=>void revokeDevice(device.id)} style={x.revoke}><Text style={x.revokeText}>Thu hồi</Text></Pressable>:null}</View>)}</View>:null}
  <View style={x.card}><Text style={x.sectionTitle}>Quyền riêng tư</Text><Text style={x.subtitle}>Daily Meals không sử dụng IMEI hoặc mã phần cứng. Phiên đăng nhập được Supabase Auth mã hóa và lưu cục bộ trên thiết bị.</Text>{apiConfigured?<Button title={busy==='logout'?'Đang đăng xuất...':'Đăng xuất trên thiết bị này'} outline onPress={()=>{setBusy('logout');void logout().finally(()=>setBusy(undefined))}}/>:null}</View>
 </Page></Screen>;
}
const x=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',gap:8},back:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontSize:25,fontWeight:'800',color:colors.primaryDark},subtitle:{fontSize:12,color:colors.muted,lineHeight:18,marginTop:3},accountCard:{backgroundColor:colors.soft,borderRadius:18,padding:16,flexDirection:'row',gap:12,alignItems:'center'},accountIcon:{width:52,height:52,borderRadius:26,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},linkedIcon:{backgroundColor:colors.primary},accountCopy:{flex:1},sectionTitle:{fontSize:17,fontWeight:'800'},installation:{fontSize:10,color:colors.muted,marginTop:6},notice:{backgroundColor:'#FFF5E3',padding:14,borderRadius:14,flexDirection:'row',gap:10},noticeTitle:{fontWeight:'800',color:'#A85D00'},card:{backgroundColor:'#fff',borderRadius:17,padding:16,gap:13,borderWidth:1,borderColor:colors.border},provider:{minHeight:52,borderWidth:1,borderColor:colors.border,borderRadius:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},providerText:{fontWeight:'700'},disabled:{opacity:.45},message:{backgroundColor:colors.soft,color:colors.primaryDark,padding:12,borderRadius:12,fontWeight:'700'},errorBox:{backgroundColor:'#FFF0ED',padding:14,borderRadius:14,gap:10},errorText:{color:colors.danger},rowBetween:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},device:{minHeight:62,flexDirection:'row',gap:10,alignItems:'center',borderTopWidth:1,borderColor:colors.border,paddingTop:10},deviceName:{fontWeight:'700'},revoke:{minHeight:44,justifyContent:'center',paddingHorizontal:8},revokeText:{color:colors.danger,fontWeight:'700'}});
