import {Meal,NutritionInfo} from './types';

type NutritionProfile='noodle'|'porridge'|'bread'|'sticky'|'rice'|'savory-cake'|'sweet';
type Seed={
 id:string;
 title:string;
 summary:string;
 sideDishes:string[];
 minutes:number;
 price:number;
 tags:string[];
 profile:NutritionProfile;
};

const nutritionProfiles:Record<NutritionProfile,Partial<NutritionInfo>>={
 noodle:{caloriesKcal:510,proteinGrams:27,carbsGrams:65,fatGrams:16,fiberGrams:5,sodiumMg:1050},
 porridge:{caloriesKcal:390,proteinGrams:22,carbsGrams:50,fatGrams:11,fiberGrams:3,sodiumMg:760},
 bread:{caloriesKcal:480,proteinGrams:22,carbsGrams:58,fatGrams:18,fiberGrams:4,sodiumMg:850},
 sticky:{caloriesKcal:470,proteinGrams:14,carbsGrams:76,fatGrams:13,fiberGrams:5,sodiumMg:400},
 rice:{caloriesKcal:560,proteinGrams:26,carbsGrams:72,fatGrams:19,fiberGrams:5,sodiumMg:850},
 'savory-cake':{caloriesKcal:390,proteinGrams:15,carbsGrams:55,fatGrams:13,fiberGrams:3,sodiumMg:720},
 sweet:{caloriesKcal:350,proteinGrams:8,carbsGrams:59,fatGrams:10,fiberGrams:3,sodiumMg:220},
};

const images:Record<string,Meal['image']>={
 'buy-pho-bo-vien':require('../assets/images/meals/ready-made/buy-pho-bo-vien.webp'),
 'buy-pho-gan':require('../assets/images/meals/ready-made/buy-pho-gan.webp'),
 'buy-pho-ap-chao':require('../assets/images/meals/ready-made/buy-pho-ap-chao.webp'),
 'buy-pho-chua-lang-son':require('../assets/images/meals/ready-made/buy-pho-chua-lang-son.webp'),
 'buy-pho-kho-gia-lai':require('../assets/images/meals/ready-made/buy-pho-kho-gia-lai.webp'),
 'buy-bun-bo-nam-bo':require('../assets/images/meals/ready-made/buy-bun-bo-nam-bo.webp'),
 'buy-bun-cha-ha-noi':require('../assets/images/meals/ready-made/buy-bun-cha-ha-noi.webp'),
 'buy-bun-doc-mung':require('../assets/images/meals/ready-made/buy-bun-doc-mung.webp'),
 'buy-bun-oc':require('../assets/images/meals/ready-made/buy-bun-oc.webp'),
 'buy-bun-thang':require('../assets/images/meals/ready-made/buy-bun-thang.webp'),
 'buy-bun-ngan':require('../assets/images/meals/ready-made/buy-bun-ngan.webp'),
 'buy-bun-ca-chau-doc':require('../assets/images/meals/ready-made/buy-bun-ca-chau-doc.webp'),
 'buy-bun-ca-kien-giang':require('../assets/images/meals/ready-made/buy-bun-ca-kien-giang.webp'),
 'buy-bun-ken':require('../assets/images/meals/ready-made/buy-bun-ken.webp'),
 'buy-bun-mam':require('../assets/images/meals/ready-made/buy-bun-mam.webp'),
 'buy-bun-thit-xao':require('../assets/images/meals/ready-made/buy-bun-thit-xao.webp'),
 'buy-bun-nem-nuong':require('../assets/images/meals/ready-made/buy-bun-nem-nuong.webp'),
 'buy-bun-dau-mam-tom':require('../assets/images/meals/ready-made/buy-bun-dau-mam-tom.webp'),
 'buy-bun-nghe':require('../assets/images/meals/ready-made/buy-bun-nghe.webp'),
 'buy-bun-ram':require('../assets/images/meals/ready-made/buy-bun-ram.webp'),
 'buy-bun-hen':require('../assets/images/meals/ready-made/buy-bun-hen.webp'),
 'buy-mi-quang-ech':require('../assets/images/meals/ready-made/buy-mi-quang-ech.webp'),
 'buy-mi-quang-ca-loc':require('../assets/images/meals/ready-made/buy-mi-quang-ca-loc.webp'),
 'buy-cao-lau':require('../assets/images/meals/ready-made/buy-cao-lau.webp'),
 'buy-mi-phu-chiem':require('../assets/images/meals/ready-made/buy-mi-phu-chiem.webp'),
 'buy-mi-suon':require('../assets/images/meals/ready-made/buy-mi-suon.webp'),
 'buy-mi-kho-xa-xiu':require('../assets/images/meals/ready-made/buy-mi-kho-xa-xiu.webp'),
 'buy-mi-ga-quay':require('../assets/images/meals/ready-made/buy-mi-ga-quay.webp'),
 'buy-hu-tieu-sa-te':require('../assets/images/meals/ready-made/buy-hu-tieu-sa-te.webp'),
 'buy-hu-tieu-bo-kho':require('../assets/images/meals/ready-made/buy-hu-tieu-bo-kho.webp'),
 'buy-hu-tieu-mi':require('../assets/images/meals/ready-made/buy-hu-tieu-mi.webp'),
 'buy-hu-tieu-ca':require('../assets/images/meals/ready-made/buy-hu-tieu-ca.webp'),
 'buy-banh-canh-ghe':require('../assets/images/meals/ready-made/buy-banh-canh-ghe.webp'),
 'buy-banh-canh-cha-ca':require('../assets/images/meals/ready-made/buy-banh-canh-cha-ca.webp'),
 'buy-banh-canh-vit':require('../assets/images/meals/ready-made/buy-banh-canh-vit.webp'),
 'buy-banh-canh-bot-loc':require('../assets/images/meals/ready-made/buy-banh-canh-bot-loc.webp'),
 'buy-chao-luon':require('../assets/images/meals/ready-made/buy-chao-luon.webp'),
 'buy-chao-hau':require('../assets/images/meals/ready-made/buy-chao-hau.webp'),
 'buy-chao-ngheu':require('../assets/images/meals/ready-made/buy-chao-ngheu.webp'),
 'buy-chao-bo':require('../assets/images/meals/ready-made/buy-chao-bo.webp'),
 'buy-chao-ech':require('../assets/images/meals/ready-made/buy-chao-ech.webp'),
 'buy-chao-trang-hot-vit-muoi':require('../assets/images/meals/ready-made/buy-chao-trang-hot-vit-muoi.webp'),
 'buy-banh-mi-ga-xe':require('../assets/images/meals/ready-made/buy-banh-mi-ga-xe.webp'),
 'buy-banh-mi-bi':require('../assets/images/meals/ready-made/buy-banh-mi-bi.webp'),
 'buy-banh-mi-cha-ca':require('../assets/images/meals/ready-made/buy-banh-mi-cha-ca.webp'),
 'buy-banh-mi-nem-nuong':require('../assets/images/meals/ready-made/buy-banh-mi-nem-nuong.webp'),
 'buy-banh-mi-bo-nuong':require('../assets/images/meals/ready-made/buy-banh-mi-bo-nuong.webp'),
 'buy-banh-mi-xuc-xich':require('../assets/images/meals/ready-made/buy-banh-mi-xuc-xich.webp'),
 'buy-banh-mi-trung':require('../assets/images/meals/ready-made/buy-banh-mi-trung.webp'),
 'buy-banh-mi-pate-cha':require('../assets/images/meals/ready-made/buy-banh-mi-pate-cha.webp'),
 'buy-banh-mi-thit-nuong':require('../assets/images/meals/ready-made/buy-banh-mi-thit-nuong.webp'),
 'buy-banh-mi-que-hai-phong':require('../assets/images/meals/ready-made/buy-banh-mi-que-hai-phong.webp'),
 'buy-banh-mi-cay-da-nang':require('../assets/images/meals/ready-made/buy-banh-mi-cay-da-nang.webp'),
 'buy-banh-mi-hap':require('../assets/images/meals/ready-made/buy-banh-mi-hap.webp'),
 'buy-banh-bao-xa-xiu':require('../assets/images/meals/ready-made/buy-banh-bao-xa-xiu.webp'),
 'buy-banh-bao-trung-muoi':require('../assets/images/meals/ready-made/buy-banh-bao-trung-muoi.webp'),
 'buy-banh-bao-kim-sa':require('../assets/images/meals/ready-made/buy-banh-bao-kim-sa.webp'),
 'buy-banh-bao-chay':require('../assets/images/meals/ready-made/buy-banh-bao-chay.webp'),
 'buy-xoi-vo':require('../assets/images/meals/ready-made/buy-xoi-vo.webp'),
 'buy-xoi-gac':require('../assets/images/meals/ready-made/buy-xoi-gac.webp'),
 'buy-xoi-la-cam':require('../assets/images/meals/ready-made/buy-xoi-la-cam.webp'),
 'buy-xoi-ngu-sac':require('../assets/images/meals/ready-made/buy-xoi-ngu-sac.webp'),
 'buy-xoi-dau-den':require('../assets/images/meals/ready-made/buy-xoi-dau-den.webp'),
 'buy-xoi-san':require('../assets/images/meals/ready-made/buy-xoi-san.webp'),
 'buy-xoi-chim':require('../assets/images/meals/ready-made/buy-xoi-chim.webp'),
 'buy-xoi-thit-kho':require('../assets/images/meals/ready-made/buy-xoi-thit-kho.webp'),
 'buy-xoi-pate':require('../assets/images/meals/ready-made/buy-xoi-pate.webp'),
 'buy-xoi-trung':require('../assets/images/meals/ready-made/buy-xoi-trung.webp'),
 'buy-xoi-cade':require('../assets/images/meals/ready-made/buy-xoi-cade.webp'),
 'buy-xoi-sau-rieng':require('../assets/images/meals/ready-made/buy-xoi-sau-rieng.webp'),
 'buy-com-nam-muoi-vung':require('../assets/images/meals/ready-made/buy-com-nam-muoi-vung.webp'),
 'buy-com-nam-ca-ngu':require('../assets/images/meals/ready-made/buy-com-nam-ca-ngu.webp'),
 'buy-com-nam-thit-nuong':require('../assets/images/meals/ready-made/buy-com-nam-thit-nuong.webp'),
 'buy-com-chien-trung':require('../assets/images/meals/ready-made/buy-com-chien-trung.webp'),
 'buy-com-chien-ca-man':require('../assets/images/meals/ready-made/buy-com-chien-ca-man.webp'),
 'buy-com-ga-tam-ky':require('../assets/images/meals/ready-made/buy-com-ga-tam-ky.webp'),
 'buy-com-ga-nha-trang':require('../assets/images/meals/ready-made/buy-com-ga-nha-trang.webp'),
 'buy-banh-tam-bi':require('../assets/images/meals/ready-made/buy-banh-tam-bi.webp'),
 'buy-banh-tam-cay':require('../assets/images/meals/ready-made/buy-banh-tam-cay.webp'),
 'buy-banh-uot-long-ga':require('../assets/images/meals/ready-made/buy-banh-uot-long-ga.webp'),
 'buy-banh-uot-thit-nuong':require('../assets/images/meals/ready-made/buy-banh-uot-thit-nuong.webp'),
 'buy-banh-cuon-cao-bang':require('../assets/images/meals/ready-made/buy-banh-cuon-cao-bang.webp'),
 'buy-banh-cuon-phu-ly':require('../assets/images/meals/ready-made/buy-banh-cuon-phu-ly.webp'),
 'buy-banh-cuon-trung-lang-son':require('../assets/images/meals/ready-made/buy-banh-cuon-trung-lang-son.webp'),
 'buy-banh-beo-hai-phong':require('../assets/images/meals/ready-made/buy-banh-beo-hai-phong.webp'),
 'buy-banh-nam':require('../assets/images/meals/ready-made/buy-banh-nam.webp'),
 'buy-banh-bot-loc':require('../assets/images/meals/ready-made/buy-banh-bot-loc.webp'),
 'buy-banh-it-tran':require('../assets/images/meals/ready-made/buy-banh-it-tran.webp'),
 'buy-banh-ram-it':require('../assets/images/meals/ready-made/buy-banh-ram-it.webp'),
 'buy-banh-duc-nong':require('../assets/images/meals/ready-made/buy-banh-duc-nong.webp'),
 'buy-banh-duc-man':require('../assets/images/meals/ready-made/buy-banh-duc-man.webp'),
 'buy-banh-duc-lac':require('../assets/images/meals/ready-made/buy-banh-duc-lac.webp'),
 'buy-banh-ran-man':require('../assets/images/meals/ready-made/buy-banh-ran-man.webp'),
 'buy-banh-ran-ngot':require('../assets/images/meals/ready-made/buy-banh-ran-ngot.webp'),
 'buy-banh-tieu':require('../assets/images/meals/ready-made/buy-banh-tieu.webp'),
 'buy-banh-bo-nuong':require('../assets/images/meals/ready-made/buy-banh-bo-nuong.webp'),
 'buy-banh-bo-hap':require('../assets/images/meals/ready-made/buy-banh-bo-hap.webp'),
 'buy-banh-cam':require('../assets/images/meals/ready-made/buy-banh-cam.webp'),
 'buy-banh-cong':require('../assets/images/meals/ready-made/buy-banh-cong.webp'),
 'buy-banh-khoai-hue':require('../assets/images/meals/ready-made/buy-banh-khoai-hue.webp'),
};

const seeds:Seed[]=[
 {id:'buy-pho-bo-vien',title:'Phở bò viên',summary:'Bò viên dai mềm trong nước phở nóng, dễ ăn.',sideDishes:['Rau thơm','Giá đỗ'],minutes:12,price:50000,tags:['popular','family','south'],profile:'noodle'},
 {id:'buy-pho-gan',title:'Phở gân',summary:'Gân bò mềm giòn tạo lựa chọn phở giàu đạm.',sideDishes:['Rau thơm','Chanh'],minutes:15,price:60000,tags:['high-protein','hearty','north'],profile:'noodle'},
 {id:'buy-pho-ap-chao',title:'Phở áp chảo',summary:'Sợi phở áp chảo thơm với bò và rau cải.',sideDishes:['Rau cải','Nước tương'],minutes:15,price:60000,tags:['variety','high-protein'],profile:'noodle'},
 {id:'buy-pho-chua-lang-son',title:'Phở chua Lạng Sơn',summary:'Phở trộn chua ngọt với xá xíu và khoai chiên đặc trưng.',sideDishes:['Lạc rang','Rau thơm'],minutes:18,price:50000,tags:['regional','north','variety'],profile:'noodle'},
 {id:'buy-pho-kho-gia-lai',title:'Phở khô Gia Lai',summary:'Phở hai tô với sợi trộn và nước dùng riêng.',sideDishes:['Nước dùng','Rau sống'],minutes:18,price:55000,tags:['regional','central','variety'],profile:'noodle'},
 {id:'buy-bun-bo-nam-bo',title:'Bún bò Nam Bộ',summary:'Bún trộn bò xào, rau và lạc, tiện ăn nhanh.',sideDishes:['Rau sống','Lạc rang'],minutes:12,price:55000,tags:['popular','takeaway','north'],profile:'noodle'},
 {id:'buy-bun-cha-ha-noi',title:'Bún chả Hà Nội',summary:'Chả nướng thơm ăn cùng bún, rau và nước chấm.',sideDishes:['Rau sống','Đu đủ chua'],minutes:18,price:55000,tags:['regional','north','popular'],profile:'noodle'},
 {id:'buy-bun-doc-mung',title:'Bún dọc mùng',summary:'Sườn mềm và dọc mùng giòn trong nước dùng thanh.',sideDishes:['Rau thơm','Chanh'],minutes:15,price:50000,tags:['regional','north','family'],profile:'noodle'},
 {id:'buy-bun-oc',title:'Bún ốc',summary:'Ốc giòn, cà chua và rau thơm tạo vị chua dịu.',sideDishes:['Tía tô','Bắp chuối'],minutes:15,price:50000,tags:['regional','north','variety'],profile:'noodle'},
 {id:'buy-bun-thang',title:'Bún thang',summary:'Món bún Hà Nội thanh nhẹ với gà, trứng và chả.',sideDishes:['Rau răm','Chanh'],minutes:18,price:60000,tags:['regional','north','family'],profile:'noodle'},
 {id:'buy-bun-ngan',title:'Bún ngan',summary:'Thịt ngan mềm và măng trong nước dùng nóng.',sideDishes:['Măng','Rau thơm'],minutes:15,price:55000,tags:['regional','north','hearty'],profile:'noodle'},
 {id:'buy-bun-ca-chau-doc',title:'Bún cá Châu Đốc',summary:'Cá lóc nghệ và rau miền Tây cho bữa sáng thanh.',sideDishes:['Bắp chuối','Rau thơm'],minutes:15,price:50000,tags:['regional','south','healthy'],profile:'noodle'},
 {id:'buy-bun-ca-kien-giang',title:'Bún cá Kiên Giang',summary:'Cá và tôm trong nước dùng biển nhẹ vị.',sideDishes:['Giá đỗ','Hẹ'],minutes:15,price:55000,tags:['regional','south','seafood'],profile:'noodle'},
 {id:'buy-bun-ken',title:'Bún kèn Phú Quốc',summary:'Cá xay và nước cốt dừa tạo hương vị đảo đặc trưng.',sideDishes:['Đu đủ bào','Rau thơm'],minutes:18,price:55000,tags:['regional','south','seafood'],profile:'noodle'},
 {id:'buy-bun-mam',title:'Bún mắm',summary:'Nước lèo đậm vị với cá, tôm và heo quay.',sideDishes:['Rau sống','Bắp chuối'],minutes:18,price:65000,tags:['regional','south','hearty'],profile:'noodle'},
 {id:'buy-bun-thit-xao',title:'Bún thịt xào',summary:'Thịt xào sả ăn cùng bún và rau, dễ mang đi.',sideDishes:['Rau sống','Đồ chua'],minutes:12,price:50000,tags:['takeaway','south','popular'],profile:'noodle'},
 {id:'buy-bun-nem-nuong',title:'Bún nem nướng',summary:'Nem nướng thơm kết hợp bún, rau và nước chấm.',sideDishes:['Rau sống','Đồ chua'],minutes:12,price:50000,tags:['takeaway','central','popular'],profile:'noodle'},
 {id:'buy-bun-dau-mam-tom',title:'Bún đậu mắm tôm',summary:'Bún, đậu, thịt và rau trong một mẹt đầy đủ.',sideDishes:['Rau thơm','Mắm tôm'],minutes:18,price:60000,tags:['regional','north','hearty'],profile:'noodle'},
 {id:'buy-bun-nghe',title:'Bún nghệ Huế',summary:'Bún xào nghệ đậm màu với lòng và rau răm.',sideDishes:['Rau răm','Ớt'],minutes:12,price:40000,tags:['regional','central','budget'],profile:'noodle'},
 {id:'buy-bun-ram',title:'Bún ram Quảng Trị',summary:'Ram giòn ăn cùng bún, rau và nước mắm chua ngọt.',sideDishes:['Rau sống','Nước mắm'],minutes:12,price:40000,tags:['regional','central','budget'],profile:'noodle'},
 {id:'buy-bun-hen',title:'Bún hến Huế',summary:'Hến, rau thơm và lạc tạo phần bún cay giòn.',sideDishes:['Nước hến','Rau thơm'],minutes:15,price:40000,tags:['regional','central','variety'],profile:'noodle'},
 {id:'buy-mi-quang-ech',title:'Mì Quảng ếch',summary:'Ếch kho nghệ ăn cùng mì Quảng và bánh tráng.',sideDishes:['Bánh tráng','Rau sống'],minutes:18,price:60000,tags:['regional','central','variety'],profile:'noodle'},
 {id:'buy-mi-quang-ca-loc',title:'Mì Quảng cá lóc',summary:'Cá lóc mềm, mì nghệ và rau sống tạo phần ăn đủ chất.',sideDishes:['Bánh tráng','Rau sống'],minutes:18,price:55000,tags:['regional','central','healthy'],profile:'noodle'},
 {id:'buy-cao-lau',title:'Cao lầu Hội An',summary:'Sợi cao lầu dai với xá xíu và rau Hội An.',sideDishes:['Rau sống','Da heo giòn'],minutes:18,price:55000,tags:['regional','central','popular'],profile:'noodle'},
 {id:'buy-mi-phu-chiem',title:'Mì Phú Chiêm',summary:'Mì tôm thịt đậm đà mang hương vị Quảng Nam.',sideDishes:['Bánh tráng','Rau sống'],minutes:18,price:50000,tags:['regional','central','variety'],profile:'noodle'},
 {id:'buy-mi-suon',title:'Mì sườn',summary:'Mì trứng và sườn mềm trong nước dùng nóng.',sideDishes:['Cải xanh','Hành lá'],minutes:12,price:50000,tags:['family','hearty'],profile:'noodle'},
 {id:'buy-mi-kho-xa-xiu',title:'Mì khô xá xíu',summary:'Mì trộn xá xíu kèm chén nước dùng riêng.',sideDishes:['Nước dùng','Cải xanh'],minutes:12,price:50000,tags:['takeaway','popular'],profile:'noodle'},
 {id:'buy-mi-ga-quay',title:'Mì gà quay',summary:'Đùi gà quay và mì trứng tạo bữa sáng giàu đạm.',sideDishes:['Cải thìa','Hành lá'],minutes:15,price:60000,tags:['high-protein','hearty'],profile:'noodle'},
 {id:'buy-hu-tieu-sa-te',title:'Hủ tiếu sa tế',summary:'Nước sa tế đậu phộng thơm béo ăn cùng thịt bò.',sideDishes:['Dưa leo','Rau thơm'],minutes:15,price:55000,tags:['south','variety'],profile:'noodle'},
 {id:'buy-hu-tieu-bo-kho',title:'Hủ tiếu bò kho',summary:'Bò hầm mềm và sợi hủ tiếu cho ngày cần ăn chắc.',sideDishes:['Rau thơm','Chanh'],minutes:15,price:60000,tags:['south','hearty'],profile:'noodle'},
 {id:'buy-hu-tieu-mi',title:'Hủ tiếu mì',summary:'Hai loại sợi với thịt, tôm và trứng trong nước dùng thanh.',sideDishes:['Giá đỗ','Hẹ'],minutes:15,price:55000,tags:['south','family'],profile:'noodle'},
 {id:'buy-hu-tieu-ca',title:'Hủ tiếu cá',summary:'Cá trắng và rau cải tạo tô hủ tiếu nhẹ bụng.',sideDishes:['Cải xanh','Hẹ'],minutes:15,price:55000,tags:['seafood','healthy','south'],profile:'noodle'},
 {id:'buy-banh-canh-ghe',title:'Bánh canh ghẹ',summary:'Ghẹ và tôm trong nước dùng hải sản sánh nhẹ.',sideDishes:['Rau thơm','Chanh'],minutes:18,price:75000,tags:['seafood','south','premium'],profile:'noodle'},
 {id:'buy-banh-canh-cha-ca',title:'Bánh canh chả cá',summary:'Chả cá dai và sợi bánh canh mềm, dễ ăn.',sideDishes:['Rau thơm','Ớt'],minutes:12,price:45000,tags:['seafood','family','central'],profile:'noodle'},
 {id:'buy-banh-canh-vit',title:'Bánh canh vịt',summary:'Thịt vịt và măng trong tô bánh canh nóng.',sideDishes:['Rau răm','Mắm gừng'],minutes:15,price:55000,tags:['south','hearty'],profile:'noodle'},
 {id:'buy-banh-canh-bot-loc',title:'Bánh canh bột lọc',summary:'Sợi bột lọc dai trong nước dùng tôm thịt.',sideDishes:['Hành phi','Rau thơm'],minutes:15,price:50000,tags:['regional','central'],profile:'noodle'},
 {id:'buy-chao-luon',title:'Cháo lươn Nghệ An',summary:'Lươn xào nghệ thơm ăn cùng cháo nóng.',sideDishes:['Rau răm','Ớt'],minutes:15,price:50000,tags:['regional','central','high-protein'],profile:'porridge'},
 {id:'buy-chao-hau',title:'Cháo hàu',summary:'Hàu mềm giàu đạm trong cháo gừng nhẹ bụng.',sideDishes:['Gừng','Hành lá'],minutes:12,price:55000,tags:['seafood','healthy'],profile:'porridge'},
 {id:'buy-chao-ngheu',title:'Cháo nghêu',summary:'Nghêu ngọt thịt kết hợp cháo nóng và rau răm.',sideDishes:['Gừng','Rau răm'],minutes:12,price:45000,tags:['seafood','healthy'],profile:'porridge'},
 {id:'buy-chao-bo',title:'Cháo bò',summary:'Thịt bò mềm trong cháo nóng, phù hợp cả gia đình.',sideDishes:['Gừng','Hành lá'],minutes:12,price:50000,tags:['high-protein','family'],profile:'porridge'},
 {id:'buy-chao-ech',title:'Cháo ếch',summary:'Cháo trắng ăn cùng ếch kho đậm đà.',sideDishes:['Ếch kho','Hành lá'],minutes:18,price:65000,tags:['high-protein','variety'],profile:'porridge'},
 {id:'buy-chao-trang-hot-vit-muoi',title:'Cháo trắng hột vịt muối',summary:'Cháo trắng nhẹ bụng với trứng muối và dưa cải.',sideDishes:['Dưa cải','Đậu phộng'],minutes:8,price:30000,tags:['quick','budget','mild'],profile:'porridge'},
 {id:'buy-banh-mi-ga-xe',title:'Bánh mì gà xé',summary:'Gà xé, rau và đồ chua trong phần mang đi gọn nhẹ.',sideDishes:['Dưa leo','Đồ chua'],minutes:6,price:30000,tags:['quick','takeaway'],profile:'bread'},
 {id:'buy-banh-mi-bi',title:'Bánh mì bì',summary:'Bì heo trộn thính và rau tạo vị thơm bùi.',sideDishes:['Dưa leo','Đồ chua'],minutes:6,price:30000,tags:['quick','takeaway','south'],profile:'bread'},
 {id:'buy-banh-mi-cha-ca',title:'Bánh mì chả cá',summary:'Chả cá nóng, rau và tương ớt trong ổ bánh giòn.',sideDishes:['Dưa leo','Rau thơm'],minutes:6,price:30000,tags:['quick','takeaway','seafood'],profile:'bread'},
 {id:'buy-banh-mi-nem-nuong',title:'Bánh mì nem nướng',summary:'Nem nướng thơm, đồ chua và rau trong bánh mì.',sideDishes:['Dưa leo','Đồ chua'],minutes:7,price:35000,tags:['takeaway','central'],profile:'bread'},
 {id:'buy-banh-mi-bo-nuong',title:'Bánh mì bò nướng',summary:'Bò nướng sả giàu đạm trong phần bánh mì tiện lợi.',sideDishes:['Dưa leo','Đồ chua'],minutes:7,price:40000,tags:['takeaway','high-protein'],profile:'bread'},
 {id:'buy-banh-mi-xuc-xich',title:'Bánh mì xúc xích',summary:'Xúc xích và trứng tạo lựa chọn quen thuộc cho trẻ.',sideDishes:['Dưa leo','Đồ chua'],minutes:6,price:30000,tags:['quick','kid-friendly'],profile:'bread'},
 {id:'buy-banh-mi-trung',title:'Bánh mì trứng',summary:'Trứng chiên và pa-tê, nhanh gọn và vừa túi tiền.',sideDishes:['Dưa leo','Đồ chua'],minutes:5,price:25000,tags:['quick','budget','takeaway'],profile:'bread'},
 {id:'buy-banh-mi-pate-cha',title:'Bánh mì pa-tê chả',summary:'Pa-tê béo và chả lụa trong ổ bánh mì truyền thống.',sideDishes:['Dưa leo','Đồ chua'],minutes:5,price:30000,tags:['quick','popular','takeaway'],profile:'bread'},
 {id:'buy-banh-mi-thit-nuong',title:'Bánh mì thịt nướng',summary:'Thịt nướng thơm và rau chua ngọt, tiện mang đi.',sideDishes:['Dưa leo','Đồ chua'],minutes:7,price:35000,tags:['takeaway','popular'],profile:'bread'},
 {id:'buy-banh-mi-que-hai-phong',title:'Bánh mì que Hải Phòng',summary:'Bánh mì nhỏ giòn với pa-tê và tương ớt đặc trưng.',sideDishes:['Tương ớt','Pa-tê'],minutes:5,price:20000,tags:['regional','north','budget','quick'],profile:'bread'},
 {id:'buy-banh-mi-cay-da-nang',title:'Bánh mì cay Đà Nẵng',summary:'Ổ bánh nhỏ với chả, pa-tê và vị cay nhẹ.',sideDishes:['Tương ớt','Dưa leo'],minutes:5,price:22000,tags:['regional','central','budget','quick'],profile:'bread'},
 {id:'buy-banh-mi-hap',title:'Bánh mì hấp',summary:'Bánh mì mềm hấp cùng thịt bằm và mỡ hành.',sideDishes:['Rau thơm','Nước mắm'],minutes:12,price:35000,tags:['regional','south','variety'],profile:'bread'},
 {id:'buy-banh-bao-xa-xiu',title:'Bánh bao xá xíu',summary:'Bánh bao mềm với nhân xá xíu đậm vị.',sideDishes:['Mang đi được','Ăn nhanh'],minutes:5,price:28000,tags:['quick','takeaway'],profile:'bread'},
 {id:'buy-banh-bao-trung-muoi',title:'Bánh bao trứng muối',summary:'Nhân thịt và trứng muối tạo phần ăn chắc bụng.',sideDishes:['Mang đi được','Ăn nhanh'],minutes:5,price:32000,tags:['quick','takeaway'],profile:'bread'},
 {id:'buy-banh-bao-kim-sa',title:'Bánh bao kim sa',summary:'Nhân trứng muối chảy béo thơm trong bánh mềm.',sideDishes:['Ăn nhanh','Vị ngọt mặn'],minutes:5,price:30000,tags:['quick','variety'],profile:'sweet'},
 {id:'buy-banh-bao-chay',title:'Bánh bao chay',summary:'Nhân nấm và rau củ, gọn nhẹ cho ngày ăn chay.',sideDishes:['Mang đi được','Ăn nhanh'],minutes:5,price:25000,tags:['quick','vegetarian','takeaway'],profile:'bread'},
 {id:'buy-xoi-vo',title:'Xôi vò',summary:'Hạt xôi tơi bùi phủ đậu xanh, món sáng mộc mạc.',sideDishes:['Hành phi','Muối mè'],minutes:6,price:25000,tags:['quick','vegetarian','north'],profile:'sticky'},
 {id:'buy-xoi-gac',title:'Xôi gấc',summary:'Xôi đỏ tự nhiên, thơm nhẹ và tiện mang đi.',sideDishes:['Dừa sợi','Muối mè'],minutes:5,price:25000,tags:['quick','vegetarian','takeaway'],profile:'sticky'},
 {id:'buy-xoi-la-cam',title:'Xôi lá cẩm',summary:'Xôi tím lá cẩm thơm bùi với dừa sợi.',sideDishes:['Dừa sợi','Muối mè'],minutes:5,price:25000,tags:['quick','vegetarian','south'],profile:'sticky'},
 {id:'buy-xoi-ngu-sac',title:'Xôi ngũ sắc',summary:'Năm màu xôi tự nhiên mang nét vùng cao.',sideDishes:['Muối mè','Dừa sợi'],minutes:8,price:35000,tags:['regional','north','vegetarian'],profile:'sticky'},
 {id:'buy-xoi-dau-den',title:'Xôi đậu đen',summary:'Nếp và đậu đen tạo phần xôi bùi, no lâu.',sideDishes:['Dừa sợi','Muối mè'],minutes:5,price:22000,tags:['budget','vegetarian','quick'],profile:'sticky'},
 {id:'buy-xoi-san',title:'Xôi sắn',summary:'Xôi trộn sắn với mỡ hành và lạc rang.',sideDishes:['Hành phi','Muối mè'],minutes:6,price:25000,tags:['budget','north','quick'],profile:'sticky'},
 {id:'buy-xoi-chim',title:'Xôi chim',summary:'Xôi nghệ trộn thịt chim băm, giàu đạm và no lâu.',sideDishes:['Hành phi','Rau răm'],minutes:10,price:55000,tags:['north','high-protein','hearty'],profile:'sticky'},
 {id:'buy-xoi-thit-kho',title:'Xôi thịt kho',summary:'Xôi trắng với thịt kho và trứng, phù hợp ngày cần ăn chắc.',sideDishes:['Đồ chua','Hành lá'],minutes:8,price:45000,tags:['south','hearty','takeaway'],profile:'sticky'},
 {id:'buy-xoi-pate',title:'Xôi pa-tê',summary:'Pa-tê, chả và chà bông trên phần xôi nóng.',sideDishes:['Hành phi','Chà bông'],minutes:7,price:35000,tags:['takeaway','popular'],profile:'sticky'},
 {id:'buy-xoi-trung',title:'Xôi trứng',summary:'Xôi mặn với trứng và chả, tiện cho sáng bận rộn.',sideDishes:['Hành phi','Chà bông'],minutes:7,price:35000,tags:['quick','takeaway','family'],profile:'sticky'},
 {id:'buy-xoi-cade',title:'Xôi cadé',summary:'Xôi vàng với kem trứng dừa ngọt béo kiểu miền Nam.',sideDishes:['Dừa sợi','Mè rang'],minutes:7,price:30000,tags:['south','sweet','variety'],profile:'sweet'},
 {id:'buy-xoi-sau-rieng',title:'Xôi sầu riêng',summary:'Xôi dẻo với sầu riêng và nước cốt dừa.',sideDishes:['Nước cốt dừa','Mè rang'],minutes:8,price:40000,tags:['south','sweet','variety'],profile:'sweet'},
 {id:'buy-com-nam-muoi-vung',title:'Cơm nắm muối vừng',summary:'Cơm nắm đơn giản với muối lạc vừng, tiện mang đi.',sideDishes:['Muối vừng','Dưa leo'],minutes:5,price:20000,tags:['budget','vegetarian','takeaway'],profile:'rice'},
 {id:'buy-com-nam-ca-ngu',title:'Cơm nắm cá ngừ',summary:'Cơm nắm nhân cá ngừ, gọn nhẹ và giàu đạm.',sideDishes:['Rong biển','Dưa leo'],minutes:5,price:35000,tags:['takeaway','seafood','quick'],profile:'rice'},
 {id:'buy-com-nam-thit-nuong',title:'Cơm nắm thịt nướng',summary:'Cơm nắm nhân thịt nướng và đồ chua, chắc bụng.',sideDishes:['Đồ chua','Mè rang'],minutes:6,price:35000,tags:['takeaway','high-protein'],profile:'rice'},
 {id:'buy-com-chien-trung',title:'Cơm chiên trứng',summary:'Cơm chiên vàng với trứng và rau củ, trẻ dễ ăn.',sideDishes:['Dưa leo','Cà chua'],minutes:10,price:40000,tags:['kid-friendly','family','budget'],profile:'rice'},
 {id:'buy-com-chien-ca-man',title:'Cơm chiên cá mặn',summary:'Cơm chiên thơm với cá mặn và trứng.',sideDishes:['Dưa leo','Rau thơm'],minutes:12,price:45000,tags:['south','variety'],profile:'rice'},
 {id:'buy-com-ga-tam-ky',title:'Cơm gà Tam Kỳ',summary:'Cơm nghệ và gà chặt mang phong vị Quảng Nam.',sideDishes:['Đu đủ chua','Nước dùng'],minutes:15,price:55000,tags:['regional','central','popular'],profile:'rice'},
 {id:'buy-com-ga-nha-trang',title:'Cơm gà Nha Trang',summary:'Gà luộc, cơm vàng và mắm gừng trong phần ăn đầy đủ.',sideDishes:['Đồ chua','Nước dùng'],minutes:15,price:55000,tags:['regional','central','family'],profile:'rice'},
 {id:'buy-banh-tam-bi',title:'Bánh tằm bì',summary:'Sợi bánh tằm với bì, nước cốt dừa và rau.',sideDishes:['Rau sống','Nước mắm'],minutes:15,price:45000,tags:['regional','south','variety'],profile:'noodle'},
 {id:'buy-banh-tam-cay',title:'Bánh tằm cay Cà Mau',summary:'Bánh tằm nước cà ri cay thơm đặc trưng Cà Mau.',sideDishes:['Rau sống','Giá đỗ'],minutes:18,price:50000,tags:['regional','south','hearty'],profile:'noodle'},
 {id:'buy-banh-uot-long-ga',title:'Bánh ướt lòng gà',summary:'Bánh ướt mềm ăn cùng gà xé và lòng gà.',sideDishes:['Rau thơm','Nước mắm'],minutes:15,price:50000,tags:['regional','central','high-protein'],profile:'savory-cake'},
 {id:'buy-banh-uot-thit-nuong',title:'Bánh ướt thịt nướng',summary:'Thịt nướng thơm trên bánh ướt mềm và rau.',sideDishes:['Rau sống','Nước mắm'],minutes:15,price:45000,tags:['central','popular'],profile:'savory-cake'},
 {id:'buy-banh-cuon-cao-bang',title:'Bánh cuốn Cao Bằng',summary:'Bánh cuốn dùng trong nước canh xương nóng với trứng.',sideDishes:['Nước canh','Rau thơm'],minutes:18,price:50000,tags:['regional','north','variety'],profile:'savory-cake'},
 {id:'buy-banh-cuon-phu-ly',title:'Bánh cuốn Phủ Lý',summary:'Bánh cuốn mỏng ăn cùng chả nướng và nước chấm.',sideDishes:['Chả nướng','Rau thơm'],minutes:18,price:50000,tags:['regional','north','popular'],profile:'savory-cake'},
 {id:'buy-banh-cuon-trung-lang-son',title:'Bánh cuốn trứng Lạng Sơn',summary:'Bánh cuốn bọc trứng lòng đào, mềm và nóng.',sideDishes:['Nước canh','Hành phi'],minutes:15,price:45000,tags:['regional','north','kid-friendly'],profile:'savory-cake'},
 {id:'buy-banh-beo-hai-phong',title:'Bánh bèo Hải Phòng',summary:'Bánh bèo lá nhân thịt mộc nhĩ với nước chấm nóng.',sideDishes:['Nước chấm','Hành phi'],minutes:15,price:40000,tags:['regional','north','budget'],profile:'savory-cake'},
 {id:'buy-banh-nam',title:'Bánh nậm Huế',summary:'Bánh bột gạo mỏng với tôm thịt trong lá chuối.',sideDishes:['Nước mắm','Đồ chua'],minutes:12,price:35000,tags:['regional','central','mild'],profile:'savory-cake'},
 {id:'buy-banh-bot-loc',title:'Bánh bột lọc Huế',summary:'Bánh dai trong với nhân tôm thịt và mỡ hành.',sideDishes:['Nước mắm','Đồ chua'],minutes:12,price:40000,tags:['regional','central','popular'],profile:'savory-cake'},
 {id:'buy-banh-it-tran',title:'Bánh ít trần',summary:'Bánh nếp mềm nhân đậu thịt, phủ mỡ hành.',sideDishes:['Nước mắm','Hành phi'],minutes:12,price:35000,tags:['regional','central','mild'],profile:'savory-cake'},
 {id:'buy-banh-ram-it',title:'Bánh ram ít',summary:'Bánh ít mềm trên đế ram giòn đặc trưng Huế.',sideDishes:['Nước mắm','Tôm cháy'],minutes:12,price:40000,tags:['regional','central','variety'],profile:'savory-cake'},
 {id:'buy-banh-duc-nong',title:'Bánh đúc nóng',summary:'Bánh đúc mềm nóng với thịt bằm và mộc nhĩ.',sideDishes:['Rau thơm','Nước mắm'],minutes:10,price:35000,tags:['north','mild','budget'],profile:'savory-cake'},
 {id:'buy-banh-duc-man',title:'Bánh đúc mặn',summary:'Bánh đúc dừa với tôm thịt và đồ chua.',sideDishes:['Đồ chua','Nước mắm'],minutes:12,price:40000,tags:['south','variety'],profile:'savory-cake'},
 {id:'buy-banh-duc-lac',title:'Bánh đúc lạc',summary:'Bánh đúc lạc mộc mạc, ăn cùng muối vừng.',sideDishes:['Muối vừng','Đậu phộng'],minutes:6,price:22000,tags:['north','vegetarian','budget'],profile:'savory-cake'},
 {id:'buy-banh-ran-man',title:'Bánh rán mặn',summary:'Vỏ nếp giòn với nhân thịt và miến, tiện ăn nhanh.',sideDishes:['Nước chấm','Đồ chua'],minutes:8,price:30000,tags:['north','takeaway','budget'],profile:'savory-cake'},
 {id:'buy-banh-ran-ngot',title:'Bánh rán ngọt',summary:'Bánh nếp mè giòn với nhân đậu xanh ngọt nhẹ.',sideDishes:['Mè rang','Ăn nhanh'],minutes:5,price:20000,tags:['sweet','vegetarian','budget'],profile:'sweet'},
 {id:'buy-banh-tieu',title:'Bánh tiêu',summary:'Bánh chiên rỗng ruột, thơm mè và tiện mang đi.',sideDishes:['Mè rang','Ăn nhanh'],minutes:5,price:15000,tags:['sweet','vegetarian','budget','quick'],profile:'sweet'},
 {id:'buy-banh-bo-nuong',title:'Bánh bò nướng',summary:'Bánh lá dứa nướng với thớ tổ ong thơm dừa.',sideDishes:['Trà nóng','Dừa'],minutes:5,price:25000,tags:['sweet','vegetarian','south'],profile:'sweet'},
 {id:'buy-banh-bo-hap',title:'Bánh bò hấp',summary:'Bánh bò mềm xốp nhiều màu, phủ dừa sợi.',sideDishes:['Dừa sợi','Mè rang'],minutes:5,price:22000,tags:['sweet','vegetarian','budget'],profile:'sweet'},
 {id:'buy-banh-cam',title:'Bánh cam',summary:'Bánh nếp mè giòn với nhân đậu xanh và lớp đường.',sideDishes:['Mè rang','Ăn nhanh'],minutes:5,price:18000,tags:['sweet','vegetarian','budget'],profile:'sweet'},
 {id:'buy-banh-cong',title:'Bánh cống Sóc Trăng',summary:'Bánh chiên giòn với tôm, đậu xanh và rau sống.',sideDishes:['Rau sống','Nước mắm'],minutes:15,price:45000,tags:['regional','south','variety'],profile:'savory-cake'},
 {id:'buy-banh-khoai-hue',title:'Bánh khoái Huế',summary:'Bánh giòn tôm thịt ăn cùng rau và nước lèo đậu phộng.',sideDishes:['Rau sống','Nước lèo'],minutes:18,price:50000,tags:['regional','central','popular'],profile:'savory-cake'},
];

export const expandedReadyMadeBreakfasts2:Meal[]=seeds.map(seed=>({
 id:seed.id,
 slug:seed.id,
 type:'breakfast',
 title:seed.title,
 summary:seed.summary,
 sideDishes:seed.sideDishes,
 image:images[seed.id],
 cookingTimeMinutes:seed.minutes,
 purchaseTimeMinutes:seed.minutes,
 pricePerServing:seed.price,
 estimatedCost:seed.price*4,
 servings:4,
 missingIngredients:[],
 status:'unconfirmed',
 mealSource:'ready_made',
 cuisine:'vietnamese',
 difficulty:'easy',
 tags:['ready-made',...seed.tags],
 nutrition:{
  ...nutritionProfiles[seed.profile],
  perServing:true,
  estimateMethod:'editorial_serving_profile',
 },
}));
