import {Meal,NutritionInfo} from './types';

type ReadyMadeSeed={
 id:string;
 title:string;
 summary:string;
 sideDishes:string[];
 minutes:number;
 price:number;
 tags:string[];
 nutrition:Partial<NutritionInfo>;
};

const nutrition=(caloriesKcal:number,proteinGrams:number,carbsGrams:number,fatGrams:number,fiberGrams:number,sodiumMg:number):Partial<NutritionInfo>=>({
 caloriesKcal,proteinGrams,carbsGrams,fatGrams,fiberGrams,sodiumMg,
 perServing:true,estimateMethod:'editorial_serving_estimate',
});

const images:Record<string,Meal['image']>={
 'buy-pho-ga':require('../assets/images/meals/ready-made/buy-pho-ga.webp'),
 'buy-pho-tai-nam':require('../assets/images/meals/ready-made/buy-pho-tai-nam.webp'),
 'buy-pho-sot-vang':require('../assets/images/meals/ready-made/buy-pho-sot-vang.webp'),
 'buy-bun-moc':require('../assets/images/meals/ready-made/buy-bun-moc.webp'),
 'buy-bun-mang-vit':require('../assets/images/meals/ready-made/buy-bun-mang-vit.webp'),
 'buy-bun-ca':require('../assets/images/meals/ready-made/buy-bun-ca.webp'),
 'buy-bun-quay':require('../assets/images/meals/ready-made/buy-bun-quay.webp'),
 'buy-bun-sua':require('../assets/images/meals/ready-made/buy-bun-sua.webp'),
 'buy-bun-cha-ca':require('../assets/images/meals/ready-made/buy-bun-cha-ca.webp'),
 'buy-bun-nuoc-leo':require('../assets/images/meals/ready-made/buy-bun-nuoc-leo.webp'),
 'buy-hu-tieu-nam-vang':require('../assets/images/meals/ready-made/buy-hu-tieu-nam-vang.webp'),
 'buy-hu-tieu-kho':require('../assets/images/meals/ready-made/buy-hu-tieu-kho.webp'),
 'buy-mi-vit-tiem':require('../assets/images/meals/ready-made/buy-mi-vit-tiem.webp'),
 'buy-mi-bo-vien':require('../assets/images/meals/ready-made/buy-mi-bo-vien.webp'),
 'buy-nui-thit-bam':require('../assets/images/meals/ready-made/buy-nui-thit-bam.webp'),
 'buy-chao-ga':require('../assets/images/meals/ready-made/buy-chao-ga.webp'),
 'buy-chao-suon':require('../assets/images/meals/ready-made/buy-chao-suon.webp'),
 'buy-chao-ca':require('../assets/images/meals/ready-made/buy-chao-ca.webp'),
 'buy-chao-vit':require('../assets/images/meals/ready-made/buy-chao-vit.webp'),
 'buy-banh-mi-chao':require('../assets/images/meals/ready-made/buy-banh-mi-chao.webp'),
 'buy-banh-mi-xiu-mai':require('../assets/images/meals/ready-made/buy-banh-mi-xiu-mai.webp'),
 'buy-banh-mi-pha-lau':require('../assets/images/meals/ready-made/buy-banh-mi-pha-lau.webp'),
 'buy-banh-mi-heo-quay':require('../assets/images/meals/ready-made/buy-banh-mi-heo-quay.webp'),
 'buy-banh-mi-ca':require('../assets/images/meals/ready-made/buy-banh-mi-ca.webp'),
 'buy-xoi-xeo':require('../assets/images/meals/ready-made/buy-xoi-xeo.webp'),
 'buy-xoi-khuc':require('../assets/images/meals/ready-made/buy-xoi-khuc.webp'),
 'buy-xoi-dau-xanh':require('../assets/images/meals/ready-made/buy-xoi-dau-xanh.webp'),
 'buy-xoi-bap':require('../assets/images/meals/ready-made/buy-xoi-bap.webp'),
 'buy-xoi-lac':require('../assets/images/meals/ready-made/buy-xoi-lac.webp'),
 'buy-banh-beo':require('../assets/images/meals/ready-made/buy-banh-beo.webp'),
 'buy-banh-hoi-long-heo':require('../assets/images/meals/ready-made/buy-banh-hoi-long-heo.webp'),
 'buy-banh-hoi-heo-quay':require('../assets/images/meals/ready-made/buy-banh-hoi-heo-quay.webp'),
 'buy-banh-can':require('../assets/images/meals/ready-made/buy-banh-can.webp'),
 'buy-banh-dap':require('../assets/images/meals/ready-made/buy-banh-dap.webp'),
 'buy-banh-da-cua':require('../assets/images/meals/ready-made/buy-banh-da-cua.webp'),
 'buy-banh-da-ca-ro':require('../assets/images/meals/ready-made/buy-banh-da-ca-ro.webp'),
 'buy-banh-canh-cua':require('../assets/images/meals/ready-made/buy-banh-canh-cua.webp'),
 'buy-banh-canh-ca-loc':require('../assets/images/meals/ready-made/buy-banh-canh-ca-loc.webp'),
 'buy-banh-canh-trang-bang':require('../assets/images/meals/ready-made/buy-banh-canh-trang-bang.webp'),
 'buy-com-hen':require('../assets/images/meals/ready-made/buy-com-hen.webp'),
 'buy-com-ga-hoi-an':require('../assets/images/meals/ready-made/buy-com-ga-hoi-an.webp'),
 'buy-bo-ne':require('../assets/images/meals/ready-made/buy-bo-ne.webp'),
 'buy-pha-lau-bo':require('../assets/images/meals/ready-made/buy-pha-lau-bo.webp'),
 'buy-lagu-ga-banh-mi':require('../assets/images/meals/ready-made/buy-lagu-ga-banh-mi.webp'),
 'buy-sup-cua':require('../assets/images/meals/ready-made/buy-sup-cua.webp'),
 'buy-trung-vit-lon':require('../assets/images/meals/ready-made/buy-trung-vit-lon.webp'),
 'buy-tau-hu-nong':require('../assets/images/meals/ready-made/buy-tau-hu-nong.webp'),
 'buy-pho-chay':require('../assets/images/meals/ready-made/buy-pho-chay.webp'),
 'buy-bun-hue-chay':require('../assets/images/meals/ready-made/buy-bun-hue-chay.webp'),
 'buy-banh-mi-chay':require('../assets/images/meals/ready-made/buy-banh-mi-chay.webp'),
};

const seeds:ReadyMadeSeed[]=[
 {id:'buy-pho-ga',title:'Phở gà',summary:'Nước dùng thanh, thịt gà mềm và phù hợp cả gia đình.',sideDishes:['Rau thơm','Chanh'],minutes:12,price:48000,tags:['ready-made','popular','family','north'],nutrition:nutrition(450,28,58,12,4,1020)},
 {id:'buy-pho-tai-nam',title:'Phở tái nạm',summary:'Lựa chọn phở bò nhiều đạm, no lâu cho buổi sáng.',sideDishes:['Rau thơm','Giá đỗ'],minutes:12,price:55000,tags:['ready-made','popular','high-protein','north'],nutrition:nutrition(520,32,60,17,4,1180)},
 {id:'buy-pho-sot-vang',title:'Phở sốt vang',summary:'Bò hầm mềm và nước dùng đậm vị cho ngày cần nhiều năng lượng.',sideDishes:['Rau thơm','Tương ớt'],minutes:15,price:60000,tags:['ready-made','hearty','north'],nutrition:nutrition(590,33,66,22,5,1210)},
 {id:'buy-bun-moc',title:'Bún mọc',summary:'Nước dùng trong và mọc nấm nhẹ vị, dễ ăn.',sideDishes:['Rau sống','Chanh'],minutes:12,price:45000,tags:['ready-made','mild','family','north'],nutrition:nutrition(440,25,58,12,4,990)},
 {id:'buy-bun-mang-vit',title:'Bún măng vịt',summary:'Thịt vịt mềm, măng giòn và nước dùng nóng bụng.',sideDishes:['Rau răm','Gừng'],minutes:15,price:55000,tags:['ready-made','hearty','south'],nutrition:nutrition(560,31,60,22,5,1080)},
 {id:'buy-bun-ca',title:'Bún cá',summary:'Cá và rau tạo thành bữa sáng thanh nhưng đủ chất.',sideDishes:['Rau cần','Chanh'],minutes:12,price:45000,tags:['ready-made','healthy','low-oil','north'],nutrition:nutrition(430,27,58,10,6,950)},
 {id:'buy-bun-quay',title:'Bún quậy Phú Quốc',summary:'Món bún hải sản tươi với phần nước chấm tự pha đặc trưng.',sideDishes:['Nước chấm quất','Rau thơm'],minutes:18,price:65000,tags:['ready-made','regional','seafood','south'],nutrition:nutrition(500,30,62,14,3,1100)},
 {id:'buy-bun-sua',title:'Bún sứa Nha Trang',summary:'Sứa giòn, chả cá và nước dùng thanh tạo cảm giác nhẹ bụng.',sideDishes:['Rau sống','Chanh'],minutes:15,price:55000,tags:['ready-made','regional','seafood','central'],nutrition:nutrition(410,25,56,9,4,980)},
 {id:'buy-bun-cha-ca',title:'Bún chả cá',summary:'Chả cá dai ngon và nước dùng dễ ăn cho cả nhà.',sideDishes:['Rau sống','Ớt'],minutes:12,price:45000,tags:['ready-made','regional','family','central'],nutrition:nutrition(450,27,59,11,5,1060)},
 {id:'buy-bun-nuoc-leo',title:'Bún nước lèo Sóc Trăng',summary:'Hương vị miền Tây đặc trưng với cá, tôm và heo quay.',sideDishes:['Bắp chuối','Rau thơm'],minutes:18,price:55000,tags:['ready-made','regional','variety','south'],nutrition:nutrition(540,31,62,19,6,1240)},
 {id:'buy-hu-tieu-nam-vang',title:'Hủ tiếu Nam Vang',summary:'Một tô đầy đủ thịt, tôm và trứng cho buổi sáng chắc bụng.',sideDishes:['Giá đỗ','Hẹ'],minutes:15,price:55000,tags:['ready-made','popular','family','south'],nutrition:nutrition(560,32,66,18,5,1140)},
 {id:'buy-hu-tieu-kho',title:'Hủ tiếu khô',summary:'Sợi hủ tiếu trộn đậm đà, kèm chén nước dùng riêng.',sideDishes:['Nước dùng','Giá đỗ'],minutes:15,price:55000,tags:['ready-made','takeaway','south'],nutrition:nutrition(570,30,72,18,4,1120)},
 {id:'buy-mi-vit-tiem',title:'Mì vịt tiềm',summary:'Đùi vịt mềm và nước dùng thảo mộc cho bữa sáng no lâu.',sideDishes:['Cải thìa','Nấm hương'],minutes:18,price:70000,tags:['ready-made','hearty','high-protein'],nutrition:nutrition(650,36,68,27,5,1300)},
 {id:'buy-mi-bo-vien',title:'Mì bò viên',summary:'Mì trứng và bò viên quen thuộc, hợp cả người lớn lẫn trẻ em.',sideDishes:['Cải xanh','Hành lá'],minutes:12,price:45000,tags:['ready-made','kid-friendly','family'],nutrition:nutrition(510,27,65,16,4,1160)},
 {id:'buy-nui-thit-bam',title:'Nui thịt bằm',summary:'Món nước mềm, dễ ăn và phù hợp trẻ nhỏ.',sideDishes:['Cà rốt','Hành lá'],minutes:10,price:40000,tags:['ready-made','kid-friendly','mild','budget'],nutrition:nutrition(430,22,60,11,4,850)},
 {id:'buy-chao-ga',title:'Cháo gà',summary:'Cháo nóng nhẹ bụng với thịt gà xé và rau răm.',sideDishes:['Quẩy','Rau răm'],minutes:10,price:40000,tags:['ready-made','mild','family','healthy'],nutrition:nutrition(390,24,50,10,2,780)},
 {id:'buy-chao-suon',title:'Cháo sườn',summary:'Cháo mịn và sườn mềm, dễ dùng trong những sáng bận rộn.',sideDishes:['Quẩy','Tiêu'],minutes:10,price:40000,tags:['ready-made','kid-friendly','mild','north'],nutrition:nutrition(420,20,55,13,2,820)},
 {id:'buy-chao-ca',title:'Cháo cá',summary:'Cá giàu đạm kết hợp cháo nóng, nhẹ bụng và ít dầu.',sideDishes:['Gừng','Hành lá'],minutes:12,price:45000,tags:['ready-made','healthy','low-oil'],nutrition:nutrition(370,25,48,8,2,760)},
 {id:'buy-chao-vit',title:'Cháo vịt',summary:'Cháo nóng kèm thịt vịt và nước mắm gừng đặc trưng.',sideDishes:['Rau răm','Mắm gừng'],minutes:15,price:50000,tags:['ready-made','hearty','south'],nutrition:nutrition(470,28,50,18,2,870)},
 {id:'buy-banh-mi-chao',title:'Bánh mì chảo',summary:'Trứng, thịt và pa-tê trong một phần ăn nóng, no lâu.',sideDishes:['Bánh mì','Dưa góp'],minutes:12,price:50000,tags:['ready-made','high-protein','popular'],nutrition:nutrition(650,30,58,34,4,1250)},
 {id:'buy-banh-mi-xiu-mai',title:'Bánh mì xíu mại',summary:'Xíu mại sốt cà chua mềm, tiện mang đi.',sideDishes:['Dưa leo','Đồ chua'],minutes:7,price:30000,tags:['ready-made','quick','takeaway','budget'],nutrition:nutrition(480,22,58,18,4,850)},
 {id:'buy-banh-mi-pha-lau',title:'Bánh mì phá lấu',summary:'Phá lấu béo thơm và bánh mì giòn cho bữa sáng đổi vị.',sideDishes:['Dưa leo','Rau răm'],minutes:8,price:35000,tags:['ready-made','takeaway','south','variety'],nutrition:nutrition(520,21,56,24,4,980)},
 {id:'buy-banh-mi-heo-quay',title:'Bánh mì heo quay',summary:'Heo quay giòn bì kết hợp đồ chua, gọn và chắc bụng.',sideDishes:['Đồ chua','Dưa leo'],minutes:7,price:35000,tags:['ready-made','quick','takeaway'],nutrition:nutrition(560,24,58,26,4,970)},
 {id:'buy-banh-mi-ca',title:'Bánh mì cá',summary:'Cá chiên và rau tạo lựa chọn bánh mì khác biệt.',sideDishes:['Dưa leo','Đồ chua'],minutes:7,price:30000,tags:['ready-made','quick','takeaway','seafood'],nutrition:nutrition(460,22,57,16,4,790)},
 {id:'buy-xoi-xeo',title:'Xôi xéo',summary:'Xôi nghệ, đậu xanh và hành phi mang hương vị miền Bắc.',sideDishes:['Muối mè','Hành phi'],minutes:7,price:25000,tags:['ready-made','quick','takeaway','budget','north'],nutrition:nutrition(480,13,78,13,5,420)},
 {id:'buy-xoi-khuc',title:'Xôi khúc',summary:'Xôi nếp bọc bánh khúc nhân đậu thịt, nhỏ gọn nhưng no lâu.',sideDishes:['Muối mè','Hành phi'],minutes:7,price:30000,tags:['ready-made','takeaway','north'],nutrition:nutrition(520,17,78,16,5,560)},
 {id:'buy-xoi-dau-xanh',title:'Xôi đậu xanh',summary:'Xôi đậu đơn giản, dễ mua và phù hợp ngân sách.',sideDishes:['Muối mè','Dừa sợi'],minutes:5,price:20000,tags:['ready-made','quick','budget','vegetarian'],nutrition:nutrition(430,12,76,9,6,260)},
 {id:'buy-xoi-bap',title:'Xôi bắp',summary:'Bắp, nếp và đậu xanh tạo vị bùi, nhẹ nhàng.',sideDishes:['Muối mè','Hành phi'],minutes:5,price:20000,tags:['ready-made','quick','budget','vegetarian'],nutrition:nutrition(410,11,74,8,7,280)},
 {id:'buy-xoi-lac',title:'Xôi lạc',summary:'Xôi nếp trộn đậu phộng, món sáng mộc mạc và chắc bụng.',sideDishes:['Muối mè','Vừng'],minutes:5,price:20000,tags:['ready-made','quick','budget','vegetarian','north'],nutrition:nutrition(450,14,72,12,6,250)},
 {id:'buy-banh-beo',title:'Bánh bèo',summary:'Bánh mềm với tôm cháy và mỡ hành, hợp sáng cuối tuần.',sideDishes:['Nước mắm','Đồ chua'],minutes:15,price:40000,tags:['ready-made','regional','central','variety'],nutrition:nutrition(390,14,58,11,3,780)},
 {id:'buy-banh-hoi-long-heo',title:'Bánh hỏi lòng heo',summary:'Đặc sản miền Trung kết hợp bánh hỏi mềm và lòng heo.',sideDishes:['Rau sống','Nước mắm'],minutes:18,price:55000,tags:['ready-made','regional','central','hearty'],nutrition:nutrition(560,29,57,24,4,1050)},
 {id:'buy-banh-hoi-heo-quay',title:'Bánh hỏi heo quay',summary:'Bánh hỏi mỡ hành ăn cùng heo quay giòn bì.',sideDishes:['Rau sống','Nước mắm'],minutes:15,price:55000,tags:['ready-made','regional','central'],nutrition:nutrition(590,27,60,27,4,1080)},
 {id:'buy-banh-can',title:'Bánh căn',summary:'Bánh căn nóng với trứng và tôm, thích hợp bữa sáng đổi vị.',sideDishes:['Xoài xanh','Nước chấm'],minutes:15,price:45000,tags:['ready-made','regional','central','variety'],nutrition:nutrition(420,19,55,14,4,720)},
 {id:'buy-banh-dap',title:'Bánh đập',summary:'Lớp bánh tráng giòn và bánh ướt mềm chấm mắm nêm.',sideDishes:['Mắm nêm','Mỡ hành'],minutes:12,price:30000,tags:['ready-made','regional','central','budget'],nutrition:nutrition(360,9,62,9,3,760)},
 {id:'buy-banh-da-cua',title:'Bánh đa cua Hải Phòng',summary:'Bánh đa đỏ, riêu cua và rau tạo tô sáng đậm chất Hải Phòng.',sideDishes:['Rau muống','Chả lá lốt'],minutes:15,price:50000,tags:['ready-made','regional','north','popular'],nutrition:nutrition(520,27,65,17,6,1160)},
 {id:'buy-banh-da-ca-ro',title:'Bánh đa cá rô',summary:'Cá rô chiên và rau cải trong nước dùng thanh.',sideDishes:['Rau cải','Thì là'],minutes:15,price:50000,tags:['ready-made','regional','north','seafood'],nutrition:nutrition(470,30,61,12,6,980)},
 {id:'buy-banh-canh-cua',title:'Bánh canh cua',summary:'Sợi bánh canh dai với cua và tôm, no lâu.',sideDishes:['Rau thơm','Chanh'],minutes:15,price:60000,tags:['ready-made','seafood','popular','south'],nutrition:nutrition(560,31,68,18,4,1190)},
 {id:'buy-banh-canh-ca-loc',title:'Bánh canh cá lóc',summary:'Cá lóc mềm, nước dùng thanh và ít dầu.',sideDishes:['Rau đắng','Ớt'],minutes:15,price:50000,tags:['ready-made','regional','healthy','central'],nutrition:nutrition(450,29,60,10,4,960)},
 {id:'buy-banh-canh-trang-bang',title:'Bánh canh Trảng Bàng',summary:'Bánh canh giò heo ăn cùng nhiều rau đặc trưng Tây Ninh.',sideDishes:['Rau rừng','Chanh'],minutes:18,price:60000,tags:['ready-made','regional','south','hearty'],nutrition:nutrition(600,31,66,24,6,1240)},
 {id:'buy-com-hen',title:'Cơm hến Huế',summary:'Cơm, hến và rau thơm tạo vị cay giòn đặc trưng xứ Huế.',sideDishes:['Nước hến','Rau thơm'],minutes:15,price:40000,tags:['ready-made','regional','central','variety'],nutrition:nutrition(470,22,65,14,7,940)},
 {id:'buy-com-ga-hoi-an',title:'Cơm gà Hội An',summary:'Cơm nghệ thơm, gà xé và rau răm cho bữa sáng no lâu.',sideDishes:['Đu đủ chua','Nước dùng'],minutes:15,price:55000,tags:['ready-made','regional','central','popular'],nutrition:nutrition(610,34,72,20,5,980)},
 {id:'buy-bo-ne',title:'Bò né',summary:'Bò, trứng và pa-tê trên chảo nóng, giàu đạm.',sideDishes:['Bánh mì','Salad'],minutes:12,price:65000,tags:['ready-made','high-protein','hearty','south'],nutrition:nutrition(680,38,52,36,4,1280)},
 {id:'buy-pha-lau-bo',title:'Phá lấu bò',summary:'Phá lấu nước cốt dừa đậm đà, ăn cùng bánh mì.',sideDishes:['Bánh mì','Rau răm'],minutes:15,price:50000,tags:['ready-made','south','variety'],nutrition:nutrition(570,25,50,29,4,1080)},
 {id:'buy-lagu-ga-banh-mi',title:'Lagu gà bánh mì',summary:'Gà hầm cà chua với khoai và cà rốt, hợp ngày cần ăn chắc.',sideDishes:['Bánh mì','Rau thơm'],minutes:15,price:50000,tags:['ready-made','family','hearty'],nutrition:nutrition(560,30,62,21,6,920)},
 {id:'buy-sup-cua',title:'Súp cua',summary:'Súp nóng mềm với cua, trứng và nấm, dễ ăn.',sideDishes:['Tiêu','Ngò rí'],minutes:8,price:35000,tags:['ready-made','quick','kid-friendly','mild'],nutrition:nutrition(300,22,32,9,3,760)},
 {id:'buy-trung-vit-lon',title:'Trứng vịt lộn',summary:'Lựa chọn giàu đạm, thường dùng nhanh cùng rau răm.',sideDishes:['Rau răm','Muối tiêu'],minutes:5,price:24000,tags:['ready-made','quick','high-protein','budget'],nutrition:nutrition(370,26,4,27,1,520)},
 {id:'buy-tau-hu-nong',title:'Tàu hũ nóng',summary:'Tàu hũ mềm với nước gừng, nhẹ bụng và không cần chờ lâu.',sideDishes:['Nước gừng','Nước cốt dừa'],minutes:5,price:20000,tags:['ready-made','quick','light','vegetarian','budget'],nutrition:nutrition(230,10,35,6,3,120)},
 {id:'buy-pho-chay',title:'Phở chay',summary:'Nước dùng rau củ, đậu hũ và nấm cho bữa sáng thanh nhẹ.',sideDishes:['Rau thơm','Chanh'],minutes:12,price:45000,tags:['ready-made','vegetarian','healthy','family'],nutrition:nutrition(390,16,60,10,7,840)},
 {id:'buy-bun-hue-chay',title:'Bún Huế chay',summary:'Vị sả cay nhẹ với đậu hũ và nấm, phù hợp ngày ăn chay.',sideDishes:['Rau sống','Chanh'],minutes:12,price:45000,tags:['ready-made','vegetarian','central','variety'],nutrition:nutrition(420,17,62,12,8,920)},
 {id:'buy-banh-mi-chay',title:'Bánh mì chay',summary:'Đậu hũ, pa-tê nấm và đồ chua trong phần mang đi gọn nhẹ.',sideDishes:['Dưa leo','Đồ chua'],minutes:6,price:25000,tags:['ready-made','vegetarian','quick','takeaway','budget'],nutrition:nutrition(410,16,57,14,7,680)},
];

export const expandedReadyMadeBreakfasts:Meal[]=seeds.map(seed=>({
 id:seed.id,
 slug:seed.id,
 type:'breakfast',
 title:seed.title,
 summary:seed.summary,
 sideDishes:seed.sideDishes,
 image:images[seed.id],
 cookingTimeMinutes:seed.minutes,
 purchaseTimeMinutes:seed.minutes,
 pricePerServing:seed.price,
 estimatedCost:seed.price*4,
 servings:4,
 missingIngredients:[],
 status:'unconfirmed',
 mealSource:'ready_made',
 cuisine:'vietnamese',
 difficulty:'easy',
 tags:seed.tags,
 nutrition:seed.nutrition,
}));
