-- Generated by scripts/catalog/prepare-production.mjs.
-- The source catalog remains content/curated-extra-recipes.json.

create or replace function public.replace_meal_recipe(
  target_meal_id text,
  target_ingredients jsonb,
  target_steps jsonb
)
returns void
language plpgsql
security definer
set search_path=''
as $$
begin
  if not exists(select 1 from public.meals where id=target_meal_id) then
    raise exception 'Unknown meal: %',target_meal_id;
  end if;
  if jsonb_typeof(target_ingredients)<>'array' or jsonb_array_length(target_ingredients)<2 then
    raise exception 'A recipe requires at least two ingredients';
  end if;
  if jsonb_typeof(target_steps)<>'array' or jsonb_array_length(target_steps)<2 then
    raise exception 'A recipe requires at least two steps';
  end if;

  delete from public.recipe_ingredients where meal_id=target_meal_id;
  delete from public.recipe_steps where meal_id=target_meal_id;

  insert into public.recipe_ingredients(
    id,meal_id,name,quantity,category,available_by_default,position,
    ingredient_id,quantity_value,unit,preparation,optional
  )
  select
    item.id,target_meal_id,item.name,item.quantity,item.category,false,item.position,
    coalesce(item.ingredient_id,catalog.id),item.quantity_value,item.unit,item.preparation,
    coalesce(item.optional,false)
  from jsonb_to_recordset(target_ingredients) as item(
    id text,name text,quantity text,category text,position integer,
    ingredient_id uuid,quantity_value numeric,unit text,preparation text,optional boolean
  )
  left join lateral (
    select id from public.ingredient_catalog
    where lower(name_vi)=lower(item.name)
    order by id limit 1
  ) catalog on true;

  insert into public.recipe_steps(id,meal_id,position,description)
  select item.id,target_meal_id,item.position,item.description
  from jsonb_to_recordset(target_steps) as item(id text,position integer,description text);
end;
$$;

revoke all on function public.replace_meal_recipe(text,jsonb,jsonb) from public,anon,authenticated;
grant execute on function public.replace_meal_recipe(text,jsonb,jsonb) to service_role;

insert into public.ingredient_catalog(slug,name_vi,category)
values
  ('ingredient-8aa9c7496f0b1bc0','Trứng gà','Thịt & Hải sản'),
  ('ingredient-71f83b080e346bf9','Bánh mì','Gia vị & Khác'),
  ('ingredient-1b3738c31116b8df','Cà chua','Rau củ'),
  ('ingredient-b3a4fa6623c780c6','Dưa leo','Rau củ'),
  ('ingredient-d212a250bc742e0e','Hành lá','Rau củ'),
  ('ingredient-06eddcf0a019e56a','Dầu ăn','Gia vị & Khác'),
  ('ingredient-48de446a60fb400f','Nước tương','Gia vị & Khác'),
  ('ingredient-e1b6ed6213aacb8d','Bún sợi lớn','Gia vị & Khác'),
  ('ingredient-c40a0ae20a542bcf','Thịt bò bắp','Thịt & Hải sản'),
  ('ingredient-8180c8310914b5dc','Chả Huế','Thịt & Hải sản'),
  ('ingredient-6d9fb7bdff652ce9','Sả','Rau củ'),
  ('ingredient-595eb4e30f3d22ff','Hành tây','Rau củ'),
  ('ingredient-44d3beb36cedcadc','Mắm ruốc Huế','Gia vị & Khác'),
  ('ingredient-d3ab1ad18e03d62b','Rau sống và giá','Rau củ'),
  ('ingredient-f9f354e30d13f3b4','Miến dong','Gia vị & Khác'),
  ('ingredient-915b873acd84e412','Thịt gà','Thịt & Hải sản'),
  ('ingredient-78882e14c13b71f8','Nấm hương','Rau củ'),
  ('ingredient-888808046948a466','Nước dùng gà','Gia vị & Khác'),
  ('ingredient-1b5d0c1a446d380a','Nước mắm','Gia vị & Khác'),
  ('ingredient-792f352f8dc73984','Gạo nếp','Gia vị & Khác'),
  ('ingredient-088f8ef4687b8f67','Hành tím','Rau củ'),
  ('ingredient-36bb6c5dfc8dd1b9','Dưa góp','Rau củ'),
  ('ingredient-4a7b188df607c3ea','Nui','Gia vị & Khác'),
  ('ingredient-7dfbc3b39d5831ad','Thịt bò','Thịt & Hải sản'),
  ('ingredient-bb82c010b31408ea','Cà rốt','Rau củ'),
  ('ingredient-2a988e9a6002bb04','Sốt cà chua','Gia vị & Khác'),
  ('ingredient-8c5eb8ada9359276','Tỏi','Rau củ'),
  ('ingredient-2afae78a79d1985a','Xà lách','Rau củ'),
  ('ingredient-ff153944d43a1430','Bánh cuốn tươi','Gia vị & Khác'),
  ('ingredient-71002f06d907b4d3','Thịt heo xay','Thịt & Hải sản'),
  ('ingredient-00bdd1373bdd232e','Nấm mèo','Rau củ'),
  ('ingredient-75c979f896d5d64a','Chả lụa','Thịt & Hải sản'),
  ('ingredient-5f18e7212ffa19ad','Rau thơm','Rau củ'),
  ('ingredient-037c5ec4a6a3031c','Nước mắm chua ngọt','Gia vị & Khác'),
  ('ingredient-fbb0eb1bb5566a39','Hủ tiếu','Gia vị & Khác'),
  ('ingredient-70a47bb2874c66ee','Thịt heo','Thịt & Hải sản'),
  ('ingredient-2fe528953a3e84ee','Nước dùng xương','Gia vị & Khác'),
  ('ingredient-daf024c71d2b3922','Hẹ','Rau củ'),
  ('ingredient-c5dee03dcd2c42b4','Giá đỗ','Rau củ'),
  ('ingredient-828017c9a96cbaf1','Thịt ba chỉ','Thịt & Hải sản'),
  ('ingredient-01a5e400a2b575c9','Nước dừa','Gia vị & Khác'),
  ('ingredient-4bc05ae244c2daf5','Đường','Gia vị & Khác'),
  ('ingredient-b352487a7245da72','Bông cải xanh','Rau củ'),
  ('ingredient-ec644d5265db2785','Ớt chuông đỏ','Rau củ'),
  ('ingredient-8496602a043d9d36','Dầu hào','Gia vị & Khác'),
  ('ingredient-ed7eacd9a2a4673d','Tôm tươi','Thịt & Hải sản'),
  ('ingredient-3829218563ab3e7c','Cá basa','Thịt & Hải sản'),
  ('ingredient-b760bef676c294e6','Dứa','Rau củ'),
  ('ingredient-e57f71dee5cce68f','Bạc hà','Rau củ'),
  ('ingredient-0adc11080ec25619','Đậu bắp','Rau củ'),
  ('ingredient-08e41947ccf5ad5d','Me chua','Gia vị & Khác'),
  ('ingredient-d107ccf7aeef7c86','Sườn non','Thịt & Hải sản'),
  ('ingredient-3e186fc7181ae801','Ớt chuông','Rau củ'),
  ('ingredient-9a4499aaf705a012','Giấm gạo','Gia vị & Khác'),
  ('ingredient-1fbe711f0d6a9200','Gừng','Rau củ'),
  ('ingredient-d3a4c14b7884d16d','Đậu hũ','Gia vị & Khác'),
  ('ingredient-2e775172530346fb','Cá diêu hồng','Thịt & Hải sản'),
  ('ingredient-f84bb73ce7c4121f','Rau mùi','Rau củ'),
  ('ingredient-434a438c0dda95bd','Dầu mè','Gia vị & Khác'),
  ('ingredient-f0863c9451dcb097','Thịt bò thăn','Thịt & Hải sản'),
  ('ingredient-0ad6a6cc6f438ee0','Khoai tây','Rau củ'),
  ('ingredient-1b3f79ddec6e0b7d','Đùi gà','Thịt & Hải sản'),
  ('ingredient-9f750a428d19fff5','Mật ong','Gia vị & Khác'),
  ('ingredient-2b23a2e2db1f62d0','Đậu Hà Lan','Rau củ'),
  ('ingredient-63cd764409844a5b','Lá giang','Rau củ'),
  ('ingredient-84a4c2c6050d8b24','Rau củ thập cẩm','Rau củ'),
  ('ingredient-a0d4de4fb79dd33b','Mắm nêm','Gia vị & Khác'),
  ('ingredient-769f8cd317971dfe','Dứa băm','Rau củ'),
  ('ingredient-caf51506588bcbbd','Chanh','Rau củ'),
  ('ingredient-f70886efa050a131','Bún tươi','Gia vị & Khác'),
  ('ingredient-c97a25cbd5e092ce','Đu đủ xanh','Rau củ'),
  ('ingredient-1372c916fba76713','Rau sống','Rau củ')
on conflict(slug) do update set
  name_vi=excluded.name_vi,
  category=excluded.category,
  updated_at=now();

create temporary table production_meal_assets(
  meal_id text primary key,
  image_path text not null
) on commit drop;

insert into production_meal_assets(meal_id,image_path)
values
  ('pho','production/pho-f4bafb2d5e282661.webp'),
  ('chao-ga','production/chao-ga-51ad7c1a80a49731.webp'),
  ('com-nam-sang','production/com-nam-sang-5f7fe2c5d0fc9f94.webp'),
  ('banh-mi-op-la','production/banh-mi-op-la-7de88cd3f6466e97.webp'),
  ('bun-bo','production/bun-bo-d26384f6fc80a719.webp'),
  ('mien-ga','production/mien-ga-fd302700b523156d.webp'),
  ('xoi-ga','production/xoi-ga-a30c21fcb4e966c8.webp'),
  ('nui-xao-bo','production/nui-xao-bo-ebaef76b72cf3da2.webp'),
  ('banh-cuon','production/banh-cuon-434ba3c964ac0de7.webp'),
  ('hu-tieu','production/hu-tieu-d16791b19453d585.webp'),
  ('com-ga','production/com-ga-f951acde53721c7c.webp'),
  ('ga-nam','production/ga-nam-bd8420f2e6903b5a.webp'),
  ('ca-trua','production/ca-trua-fc13f35b1efd110d.webp'),
  ('thit-kho-trung','production/thit-kho-trung-c47477def2d31f9b.webp'),
  ('bo-xao-bong-cai','production/bo-xao-bong-cai-b9859b11b89de22f.webp'),
  ('tom-rim','production/tom-rim-f96ff04158e8a88e.webp'),
  ('canh-chua-ca','production/canh-chua-ca-7cc398b41faab2b4.webp'),
  ('suon-xao-chua-ngot','production/suon-xao-chua-ngot-53d7096d0bcb9750.webp'),
  ('ga-kho-gung','production/ga-kho-gung-d9ed2d631d94e24f.webp'),
  ('dau-hu-nhoi-thit','production/dau-hu-nhoi-thit-83d4e261dd7a4d5a.webp'),
  ('ca','production/ca-d5f969fa584b2cf7.webp'),
  ('ga','production/ga-21974009c2099303.webp'),
  ('dau','production/dau-830912e8b9feb5c2.webp'),
  ('ca-hap-gung','production/ca-hap-gung-65d71133b894129c.webp'),
  ('bo-luc-lac','production/bo-luc-lac-c4dc7b8bb144d8e1.webp'),
  ('ga-nuong-mat-ong','production/ga-nuong-mat-ong-55f51bea31bb6239.webp'),
  ('tom-xao-rau-cu','production/tom-xao-rau-cu-041de93fcdb9e63d.webp'),
  ('canh-ga-la-giang','production/canh-ga-la-giang-96d7e0035e6ea2dd.webp'),
  ('thit-luon-rau-cu','production/thit-luon-rau-cu-1a2b7436d6cf2772.webp'),
  ('bun-cha','production/bun-cha-7fe4f80df44d288d.webp');

update public.meals meal
set
  image_path=asset.image_path,
  image_url=null,
  source_type='ai_generated',
  source_name='Daily Meals editorial (AI-assisted)',
  content_license='internal-use',
  content_version=2,
  content_status='published',
  updated_at=now()
from production_meal_assets asset
where meal.id=asset.meal_id;

select public.replace_meal_recipe(
  'banh-mi-op-la',
  '[{"id":"banh-mi-op-la-ingredient-1","name":"Trứng gà","quantity":"4 quả","category":"Thịt & Hải sản","position":1,"optional":false},{"id":"banh-mi-op-la-ingredient-2","name":"Bánh mì","quantity":"4 ổ","category":"Gia vị & Khác","position":2,"optional":false},{"id":"banh-mi-op-la-ingredient-3","name":"Cà chua","quantity":"2 quả","category":"Rau củ","position":3,"optional":false},{"id":"banh-mi-op-la-ingredient-4","name":"Dưa leo","quantity":"2 quả","category":"Rau củ","position":4,"optional":false},{"id":"banh-mi-op-la-ingredient-5","name":"Hành lá","quantity":"2 nhánh","category":"Rau củ","position":5,"optional":false},{"id":"banh-mi-op-la-ingredient-6","name":"Dầu ăn","quantity":"1 muỗng canh","category":"Gia vị & Khác","position":6,"optional":false},{"id":"banh-mi-op-la-ingredient-7","name":"Nước tương","quantity":"2 muỗng canh","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"banh-mi-op-la-step-1","position":1,"description":"Rửa sạch cà chua, dưa leo và hành lá; thái lát rau củ, cắt nhỏ hành."},{"id":"banh-mi-op-la-step-2","position":2,"description":"Làm nóng chảo với dầu, đập trứng vào và chiên lửa vừa đến khi lòng trắng chín, lòng đỏ còn mềm."},{"id":"banh-mi-op-la-step-3","position":3,"description":"Rắc hành lá và tiêu lên trứng; làm nóng bánh mì trong chảo hoặc lò 2–3 phút."},{"id":"banh-mi-op-la-step-4","position":4,"description":"Dùng trứng ngay cùng bánh mì, cà chua, dưa leo và nước tương."}]'::jsonb
);

select public.replace_meal_recipe(
  'bun-bo',
  '[{"id":"bun-bo-ingredient-1","name":"Bún sợi lớn","quantity":"700g","category":"Gia vị & Khác","position":1,"optional":false},{"id":"bun-bo-ingredient-2","name":"Thịt bò bắp","quantity":"400g","category":"Thịt & Hải sản","position":2,"optional":false},{"id":"bun-bo-ingredient-3","name":"Chả Huế","quantity":"200g","category":"Thịt & Hải sản","position":3,"optional":false},{"id":"bun-bo-ingredient-4","name":"Sả","quantity":"4 cây","category":"Rau củ","position":4,"optional":false},{"id":"bun-bo-ingredient-5","name":"Hành tây","quantity":"1 củ","category":"Rau củ","position":5,"optional":false},{"id":"bun-bo-ingredient-6","name":"Mắm ruốc Huế","quantity":"1 muỗng canh","category":"Gia vị & Khác","position":6,"optional":false},{"id":"bun-bo-ingredient-7","name":"Rau sống và giá","quantity":"400g","category":"Rau củ","position":7,"optional":false}]'::jsonb,
  '[{"id":"bun-bo-step-1","position":1,"description":"Đập dập sả, hòa mắm ruốc với nước rồi lọc lấy phần trong; thái mỏng hành tây và thịt bò."},{"id":"bun-bo-step-2","position":2,"description":"Đun nước dùng với sả 15 phút, thêm phần mắm ruốc đã lọc và nêm nước mắm, đường phèn vừa vị."},{"id":"bun-bo-step-3","position":3,"description":"Cho thịt bò vào nấu vừa chín, thêm chả Huế; chần bún qua nước sôi và chia vào tô."},{"id":"bun-bo-step-4","position":4,"description":"Xếp thịt, chả và hành tây lên bún, chan nước dùng nóng; dùng cùng rau sống và giá."}]'::jsonb
);

select public.replace_meal_recipe(
  'mien-ga',
  '[{"id":"mien-ga-ingredient-1","name":"Miến dong","quantity":"400g","category":"Gia vị & Khác","position":1,"optional":false},{"id":"mien-ga-ingredient-2","name":"Thịt gà","quantity":"500g","category":"Thịt & Hải sản","position":2,"optional":false},{"id":"mien-ga-ingredient-3","name":"Nấm hương","quantity":"100g","category":"Rau củ","position":3,"optional":false},{"id":"mien-ga-ingredient-4","name":"Hành tây","quantity":"1/2 củ","category":"Rau củ","position":4,"optional":false},{"id":"mien-ga-ingredient-5","name":"Hành lá","quantity":"3 nhánh","category":"Rau củ","position":5,"optional":false},{"id":"mien-ga-ingredient-6","name":"Nước dùng gà","quantity":"1.5 lít","category":"Gia vị & Khác","position":6,"optional":false},{"id":"mien-ga-ingredient-7","name":"Nước mắm","quantity":"2 muỗng canh","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"mien-ga-step-1","position":1,"description":"Ngâm miến và nấm hương riêng trong nước ấm; vớt ra, cắt miến vừa ăn và thái nấm."},{"id":"mien-ga-step-2","position":2,"description":"Luộc gà trong nước dùng đến chín, vớt ra để nguội rồi xé sợi; nêm nước dùng với nước mắm."},{"id":"mien-ga-step-3","position":3,"description":"Cho nấm vào nước dùng nấu 5 phút, sau đó cho miến vào nấu 1–2 phút đến vừa mềm."},{"id":"mien-ga-step-4","position":4,"description":"Chia miến ra tô, thêm gà xé, hành tây và hành lá rồi chan nước dùng nóng."}]'::jsonb
);

select public.replace_meal_recipe(
  'xoi-ga',
  '[{"id":"xoi-ga-ingredient-1","name":"Gạo nếp","quantity":"500g","category":"Gia vị & Khác","position":1,"optional":false},{"id":"xoi-ga-ingredient-2","name":"Thịt gà","quantity":"400g","category":"Thịt & Hải sản","position":2,"optional":false},{"id":"xoi-ga-ingredient-3","name":"Hành tím","quantity":"5 củ","category":"Rau củ","position":3,"optional":false},{"id":"xoi-ga-ingredient-4","name":"Hành lá","quantity":"3 nhánh","category":"Rau củ","position":4,"optional":false},{"id":"xoi-ga-ingredient-5","name":"Dưa góp","quantity":"200g","category":"Rau củ","position":5,"optional":false},{"id":"xoi-ga-ingredient-6","name":"Nước mắm","quantity":"2 muỗng canh","category":"Gia vị & Khác","position":6,"optional":false},{"id":"xoi-ga-ingredient-7","name":"Dầu ăn","quantity":"2 muỗng canh","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"xoi-ga-step-1","position":1,"description":"Ngâm gạo nếp ít nhất 4 giờ, để ráo rồi trộn với một nhúm muối."},{"id":"xoi-ga-step-2","position":2,"description":"Hấp nếp 25–30 phút đến chín dẻo; luộc gà chín, để nguội và xé sợi."},{"id":"xoi-ga-step-3","position":3,"description":"Phi vàng hành tím; trộn gà với một ít nước mắm, tiêu và phần hành phi."},{"id":"xoi-ga-step-4","position":4,"description":"Xới xôi ra đĩa, thêm gà xé, mỡ hành và hành phi; dùng kèm dưa góp."}]'::jsonb
);

select public.replace_meal_recipe(
  'nui-xao-bo',
  '[{"id":"nui-xao-bo-ingredient-1","name":"Nui","quantity":"400g","category":"Gia vị & Khác","position":1,"optional":false},{"id":"nui-xao-bo-ingredient-2","name":"Thịt bò","quantity":"300g","category":"Thịt & Hải sản","position":2,"optional":false},{"id":"nui-xao-bo-ingredient-3","name":"Cà rốt","quantity":"1 củ","category":"Rau củ","position":3,"optional":false},{"id":"nui-xao-bo-ingredient-4","name":"Hành tây","quantity":"1 củ","category":"Rau củ","position":4,"optional":false},{"id":"nui-xao-bo-ingredient-5","name":"Sốt cà chua","quantity":"3 muỗng canh","category":"Gia vị & Khác","position":5,"optional":false},{"id":"nui-xao-bo-ingredient-6","name":"Tỏi","quantity":"3 tép","category":"Rau củ","position":6,"optional":false},{"id":"nui-xao-bo-ingredient-7","name":"Xà lách","quantity":"1 cây","category":"Rau củ","position":7,"optional":false}]'::jsonb,
  '[{"id":"nui-xao-bo-step-1","position":1,"description":"Luộc nui theo thời gian trên bao bì đến vừa mềm, xả nhanh với nước và để ráo."},{"id":"nui-xao-bo-step-2","position":2,"description":"Thái mỏng thịt bò, ướp với tỏi, nước tương và tiêu 10 phút; thái cà rốt và hành tây."},{"id":"nui-xao-bo-step-3","position":3,"description":"Xào nhanh thịt bò lửa lớn rồi lấy ra; xào rau củ, thêm nui và sốt cà chua."},{"id":"nui-xao-bo-step-4","position":4,"description":"Cho thịt bò trở lại chảo, đảo đều 1 phút và dùng ngay cùng xà lách."}]'::jsonb
);

select public.replace_meal_recipe(
  'banh-cuon',
  '[{"id":"banh-cuon-ingredient-1","name":"Bánh cuốn tươi","quantity":"600g","category":"Gia vị & Khác","position":1,"optional":false},{"id":"banh-cuon-ingredient-2","name":"Thịt heo xay","quantity":"250g","category":"Thịt & Hải sản","position":2,"optional":false},{"id":"banh-cuon-ingredient-3","name":"Nấm mèo","quantity":"80g","category":"Rau củ","position":3,"optional":false},{"id":"banh-cuon-ingredient-4","name":"Hành tím","quantity":"5 củ","category":"Rau củ","position":4,"optional":false},{"id":"banh-cuon-ingredient-5","name":"Chả lụa","quantity":"200g","category":"Thịt & Hải sản","position":5,"optional":false},{"id":"banh-cuon-ingredient-6","name":"Rau thơm","quantity":"1 bó","category":"Rau củ","position":6,"optional":false},{"id":"banh-cuon-ingredient-7","name":"Nước mắm chua ngọt","quantity":"200ml","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"banh-cuon-step-1","position":1,"description":"Ngâm nấm mèo đến nở, rửa sạch và băm nhỏ; thái hành tím, cắt lát chả lụa."},{"id":"banh-cuon-step-2","position":2,"description":"Phi thơm một nửa hành tím, xào thịt heo và nấm mèo đến chín, nêm nhẹ nước mắm và tiêu."},{"id":"banh-cuon-step-3","position":3,"description":"Trải bánh cuốn, cho nhân thịt vào rồi cuộn gọn; hấp lại 2 phút nếu bánh đã nguội."},{"id":"banh-cuon-step-4","position":4,"description":"Xếp bánh với chả lụa và rau thơm, rắc hành phi; dùng cùng nước mắm chua ngọt."}]'::jsonb
);

select public.replace_meal_recipe(
  'hu-tieu',
  '[{"id":"hu-tieu-ingredient-1","name":"Hủ tiếu","quantity":"600g","category":"Gia vị & Khác","position":1,"optional":false},{"id":"hu-tieu-ingredient-2","name":"Thịt heo","quantity":"350g","category":"Thịt & Hải sản","position":2,"optional":false},{"id":"hu-tieu-ingredient-3","name":"Thịt heo xay","quantity":"150g","category":"Thịt & Hải sản","position":3,"optional":false},{"id":"hu-tieu-ingredient-4","name":"Nước dùng xương","quantity":"1.5 lít","category":"Gia vị & Khác","position":4,"optional":false},{"id":"hu-tieu-ingredient-5","name":"Hẹ","quantity":"1 bó","category":"Rau củ","position":5,"optional":false},{"id":"hu-tieu-ingredient-6","name":"Giá đỗ","quantity":"250g","category":"Rau củ","position":6,"optional":false},{"id":"hu-tieu-ingredient-7","name":"Tỏi","quantity":"4 tép","category":"Rau củ","position":7,"optional":false}]'::jsonb,
  '[{"id":"hu-tieu-step-1","position":1,"description":"Luộc thịt heo trong nước dùng đến chín, vớt ra thái mỏng; xào chín thịt xay với một ít tỏi."},{"id":"hu-tieu-step-2","position":2,"description":"Nêm nước dùng với nước mắm, muối và đường phèn; giữ sôi nhẹ để nước trong."},{"id":"hu-tieu-step-3","position":3,"description":"Chần hủ tiếu và giá trong nước sôi, để ráo rồi chia vào tô."},{"id":"hu-tieu-step-4","position":4,"description":"Thêm thịt thái, thịt xay, hẹ và tỏi phi; chan nước dùng nóng và dùng ngay."}]'::jsonb
);

select public.replace_meal_recipe(
  'thit-kho-trung',
  '[{"id":"thit-kho-trung-ingredient-1","name":"Thịt ba chỉ","quantity":"500g","category":"Thịt & Hải sản","position":1,"optional":false},{"id":"thit-kho-trung-ingredient-2","name":"Trứng gà","quantity":"4 quả","category":"Thịt & Hải sản","position":2,"optional":false},{"id":"thit-kho-trung-ingredient-3","name":"Nước dừa","quantity":"500ml","category":"Gia vị & Khác","position":3,"optional":false},{"id":"thit-kho-trung-ingredient-4","name":"Hành tím","quantity":"3 củ","category":"Rau củ","position":4,"optional":false},{"id":"thit-kho-trung-ingredient-5","name":"Tỏi","quantity":"3 tép","category":"Rau củ","position":5,"optional":false},{"id":"thit-kho-trung-ingredient-6","name":"Nước mắm","quantity":"3 muỗng canh","category":"Gia vị & Khác","position":6,"optional":false},{"id":"thit-kho-trung-ingredient-7","name":"Đường","quantity":"2 muỗng canh","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"thit-kho-trung-step-1","position":1,"description":"Cắt thịt miếng vuông, chần nhanh rồi rửa sạch; luộc chín trứng và bóc vỏ."},{"id":"thit-kho-trung-step-2","position":2,"description":"Ướp thịt với hành tỏi băm, nước mắm, đường và tiêu trong 20 phút."},{"id":"thit-kho-trung-step-3","position":3,"description":"Thắng nhẹ đường tạo màu, cho thịt vào đảo săn rồi thêm nước dừa và nấu nhỏ lửa 25 phút."},{"id":"thit-kho-trung-step-4","position":4,"description":"Cho trứng vào kho thêm 15 phút đến khi thịt mềm và nước kho trong, vị đậm vừa."}]'::jsonb
);

select public.replace_meal_recipe(
  'bo-xao-bong-cai',
  '[{"id":"bo-xao-bong-cai-ingredient-1","name":"Thịt bò","quantity":"350g","category":"Thịt & Hải sản","position":1,"optional":false},{"id":"bo-xao-bong-cai-ingredient-2","name":"Bông cải xanh","quantity":"300g","category":"Rau củ","position":2,"optional":false},{"id":"bo-xao-bong-cai-ingredient-3","name":"Ớt chuông đỏ","quantity":"1 quả","category":"Rau củ","position":3,"optional":false},{"id":"bo-xao-bong-cai-ingredient-4","name":"Cà rốt","quantity":"1 củ","category":"Rau củ","position":4,"optional":false},{"id":"bo-xao-bong-cai-ingredient-5","name":"Tỏi","quantity":"4 tép","category":"Rau củ","position":5,"optional":false},{"id":"bo-xao-bong-cai-ingredient-6","name":"Dầu hào","quantity":"2 muỗng canh","category":"Gia vị & Khác","position":6,"optional":false},{"id":"bo-xao-bong-cai-ingredient-7","name":"Dầu ăn","quantity":"1 muỗng canh","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"bo-xao-bong-cai-step-1","position":1,"description":"Thái mỏng thịt bò, ướp với một nửa tỏi, dầu hào và tiêu 10 phút."},{"id":"bo-xao-bong-cai-step-2","position":2,"description":"Cắt bông cải, ớt chuông và cà rốt vừa ăn; chần bông cải 1 phút rồi để ráo."},{"id":"bo-xao-bong-cai-step-3","position":3,"description":"Xào thịt bò lửa lớn đến vừa tái rồi lấy ra; phi phần tỏi còn lại và xào rau củ."},{"id":"bo-xao-bong-cai-step-4","position":4,"description":"Cho bò trở lại chảo, đảo nhanh 1 phút, nêm vừa ăn và tắt bếp."}]'::jsonb
);

select public.replace_meal_recipe(
  'tom-rim',
  '[{"id":"tom-rim-ingredient-1","name":"Tôm tươi","quantity":"500g","category":"Thịt & Hải sản","position":1,"optional":false},{"id":"tom-rim-ingredient-2","name":"Hành tím","quantity":"3 củ","category":"Rau củ","position":2,"optional":false},{"id":"tom-rim-ingredient-3","name":"Tỏi","quantity":"3 tép","category":"Rau củ","position":3,"optional":false},{"id":"tom-rim-ingredient-4","name":"Hành lá","quantity":"3 nhánh","category":"Rau củ","position":4,"optional":false},{"id":"tom-rim-ingredient-5","name":"Nước mắm","quantity":"2 muỗng canh","category":"Gia vị & Khác","position":5,"optional":false},{"id":"tom-rim-ingredient-6","name":"Đường","quantity":"1.5 muỗng canh","category":"Gia vị & Khác","position":6,"optional":false},{"id":"tom-rim-ingredient-7","name":"Dầu ăn","quantity":"1 muỗng canh","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"tom-rim-step-1","position":1,"description":"Cắt râu, rút chỉ lưng và rửa sạch tôm; để thật ráo."},{"id":"tom-rim-step-2","position":2,"description":"Phi thơm hành tỏi, cho tôm vào đảo lửa lớn đến khi chuyển màu."},{"id":"tom-rim-step-3","position":3,"description":"Thêm nước mắm, đường và 3 muỗng canh nước; rim lửa vừa 7–8 phút."},{"id":"tom-rim-step-4","position":4,"description":"Khi sốt sánh và bám tôm, thêm tiêu, hành lá rồi tắt bếp."}]'::jsonb
);

select public.replace_meal_recipe(
  'canh-chua-ca',
  '[{"id":"canh-chua-ca-ingredient-1","name":"Cá basa","quantity":"600g","category":"Thịt & Hải sản","position":1,"optional":false},{"id":"canh-chua-ca-ingredient-2","name":"Cà chua","quantity":"3 quả","category":"Rau củ","position":2,"optional":false},{"id":"canh-chua-ca-ingredient-3","name":"Dứa","quantity":"1/3 quả","category":"Rau củ","position":3,"optional":false},{"id":"canh-chua-ca-ingredient-4","name":"Bạc hà","quantity":"3 cây","category":"Rau củ","position":4,"optional":false},{"id":"canh-chua-ca-ingredient-5","name":"Đậu bắp","quantity":"200g","category":"Rau củ","position":5,"optional":false},{"id":"canh-chua-ca-ingredient-6","name":"Giá đỗ","quantity":"200g","category":"Rau củ","position":6,"optional":false},{"id":"canh-chua-ca-ingredient-7","name":"Me chua","quantity":"50g","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"canh-chua-ca-step-1","position":1,"description":"Rửa cá với nước muối loãng, cắt khúc; sơ chế cà chua, dứa, bạc hà và đậu bắp."},{"id":"canh-chua-ca-step-2","position":2,"description":"Dằm me với nước nóng rồi lọc; đun sôi khoảng 1.2 lít nước cùng nước me và dứa."},{"id":"canh-chua-ca-step-3","position":3,"description":"Cho cá vào nấu 7 phút, hớt bọt; thêm cà chua, bạc hà và đậu bắp."},{"id":"canh-chua-ca-step-4","position":4,"description":"Nêm nước mắm, đường cân bằng chua ngọt; thêm giá và rau thơm rồi tắt bếp."}]'::jsonb
);

select public.replace_meal_recipe(
  'suon-xao-chua-ngot',
  '[{"id":"suon-xao-chua-ngot-ingredient-1","name":"Sườn non","quantity":"600g","category":"Thịt & Hải sản","position":1,"optional":false},{"id":"suon-xao-chua-ngot-ingredient-2","name":"Dứa","quantity":"1/2 quả","category":"Rau củ","position":2,"optional":false},{"id":"suon-xao-chua-ngot-ingredient-3","name":"Ớt chuông","quantity":"2 quả","category":"Rau củ","position":3,"optional":false},{"id":"suon-xao-chua-ngot-ingredient-4","name":"Hành tây","quantity":"1 củ","category":"Rau củ","position":4,"optional":false},{"id":"suon-xao-chua-ngot-ingredient-5","name":"Tỏi","quantity":"3 tép","category":"Rau củ","position":5,"optional":false},{"id":"suon-xao-chua-ngot-ingredient-6","name":"Giấm gạo","quantity":"2 muỗng canh","category":"Gia vị & Khác","position":6,"optional":false},{"id":"suon-xao-chua-ngot-ingredient-7","name":"Đường","quantity":"2 muỗng canh","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"suon-xao-chua-ngot-step-1","position":1,"description":"Chặt sườn miếng vừa ăn, chần 2 phút rồi rửa sạch; luộc sườn thêm 12 phút và để ráo."},{"id":"suon-xao-chua-ngot-step-2","position":2,"description":"Áp chảo sườn đến vàng các mặt; pha giấm, đường, nước mắm và một ít nước."},{"id":"suon-xao-chua-ngot-step-3","position":3,"description":"Phi tỏi, xào hành tây, ớt chuông và dứa 2 phút rồi cho sườn vào."},{"id":"suon-xao-chua-ngot-step-4","position":4,"description":"Rót sốt chua ngọt, đảo lửa vừa đến khi sốt sánh và bám đều sườn."}]'::jsonb
);

select public.replace_meal_recipe(
  'ga-kho-gung',
  '[{"id":"ga-kho-gung-ingredient-1","name":"Thịt gà","quantity":"600g","category":"Thịt & Hải sản","position":1,"optional":false},{"id":"ga-kho-gung-ingredient-2","name":"Gừng","quantity":"1 củ","category":"Rau củ","position":2,"optional":false},{"id":"ga-kho-gung-ingredient-3","name":"Hành tím","quantity":"3 củ","category":"Rau củ","position":3,"optional":false},{"id":"ga-kho-gung-ingredient-4","name":"Hành lá","quantity":"3 nhánh","category":"Rau củ","position":4,"optional":false},{"id":"ga-kho-gung-ingredient-5","name":"Nước mắm","quantity":"2.5 muỗng canh","category":"Gia vị & Khác","position":5,"optional":false},{"id":"ga-kho-gung-ingredient-6","name":"Đường","quantity":"1 muỗng canh","category":"Gia vị & Khác","position":6,"optional":false},{"id":"ga-kho-gung-ingredient-7","name":"Dầu ăn","quantity":"1 muỗng canh","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"ga-kho-gung-step-1","position":1,"description":"Chặt gà miếng vừa ăn; thái sợi gừng, băm hành tím và cắt nhỏ hành lá."},{"id":"ga-kho-gung-step-2","position":2,"description":"Ướp gà với một nửa gừng, hành tím, nước mắm, đường và tiêu 15 phút."},{"id":"ga-kho-gung-step-3","position":3,"description":"Đảo gà trên lửa vừa đến săn, thêm 150ml nước và phần gừng còn lại."},{"id":"ga-kho-gung-step-4","position":4,"description":"Kho nhỏ lửa 20 phút đến khi gà chín và sốt sánh; rắc hành lá."}]'::jsonb
);

select public.replace_meal_recipe(
  'dau-hu-nhoi-thit',
  '[{"id":"dau-hu-nhoi-thit-ingredient-1","name":"Đậu hũ","quantity":"6 miếng","category":"Gia vị & Khác","position":1,"optional":false},{"id":"dau-hu-nhoi-thit-ingredient-2","name":"Thịt heo xay","quantity":"250g","category":"Thịt & Hải sản","position":2,"optional":false},{"id":"dau-hu-nhoi-thit-ingredient-3","name":"Cà chua","quantity":"4 quả","category":"Rau củ","position":3,"optional":false},{"id":"dau-hu-nhoi-thit-ingredient-4","name":"Nấm mèo","quantity":"40g","category":"Rau củ","position":4,"optional":false},{"id":"dau-hu-nhoi-thit-ingredient-5","name":"Hành tím","quantity":"2 củ","category":"Rau củ","position":5,"optional":false},{"id":"dau-hu-nhoi-thit-ingredient-6","name":"Hành lá","quantity":"3 nhánh","category":"Rau củ","position":6,"optional":false},{"id":"dau-hu-nhoi-thit-ingredient-7","name":"Nước mắm","quantity":"2 muỗng canh","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"dau-hu-nhoi-thit-step-1","position":1,"description":"Ngâm nấm mèo, băm nhỏ rồi trộn với thịt xay, hành tím, nước mắm và tiêu."},{"id":"dau-hu-nhoi-thit-step-2","position":2,"description":"Rạch một cạnh đậu hũ, lấy bớt ruột và nhồi nhân thịt vừa chặt."},{"id":"dau-hu-nhoi-thit-step-3","position":3,"description":"Áp chảo đậu hũ đến vàng nhẹ; xào mềm cà chua với một nhúm muối."},{"id":"dau-hu-nhoi-thit-step-4","position":4,"description":"Cho đậu vào sốt cà, thêm 100ml nước và nấu đậy nắp 12 phút; rắc hành lá."}]'::jsonb
);

select public.replace_meal_recipe(
  'ca-hap-gung',
  '[{"id":"ca-hap-gung-ingredient-1","name":"Cá diêu hồng","quantity":"1 con khoảng 1kg","category":"Thịt & Hải sản","position":1,"optional":false},{"id":"ca-hap-gung-ingredient-2","name":"Gừng","quantity":"1 củ","category":"Rau củ","position":2,"optional":false},{"id":"ca-hap-gung-ingredient-3","name":"Hành lá","quantity":"5 nhánh","category":"Rau củ","position":3,"optional":false},{"id":"ca-hap-gung-ingredient-4","name":"Hành tây","quantity":"1/2 củ","category":"Rau củ","position":4,"optional":false},{"id":"ca-hap-gung-ingredient-5","name":"Rau mùi","quantity":"1 bó nhỏ","category":"Rau củ","position":5,"optional":false},{"id":"ca-hap-gung-ingredient-6","name":"Nước tương","quantity":"3 muỗng canh","category":"Gia vị & Khác","position":6,"optional":false},{"id":"ca-hap-gung-ingredient-7","name":"Dầu mè","quantity":"1 muỗng cà phê","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"ca-hap-gung-step-1","position":1,"description":"Làm sạch cá, khứa nhẹ hai mặt; thái sợi gừng, hành tây và hành lá."},{"id":"ca-hap-gung-step-2","position":2,"description":"Đặt một nửa gừng hành dưới cá, phần còn lại phủ lên trên; rưới nước tương."},{"id":"ca-hap-gung-step-3","position":3,"description":"Hấp cá khi nước đã sôi trong 18–22 phút tùy kích thước, đến khi thịt cá tách dễ."},{"id":"ca-hap-gung-step-4","position":4,"description":"Rưới dầu mè, thêm rau mùi và dùng nóng cùng rau luộc."}]'::jsonb
);

select public.replace_meal_recipe(
  'bo-luc-lac',
  '[{"id":"bo-luc-lac-ingredient-1","name":"Thịt bò thăn","quantity":"500g","category":"Thịt & Hải sản","position":1,"optional":false},{"id":"bo-luc-lac-ingredient-2","name":"Khoai tây","quantity":"3 củ","category":"Rau củ","position":2,"optional":false},{"id":"bo-luc-lac-ingredient-3","name":"Ớt chuông","quantity":"2 quả","category":"Rau củ","position":3,"optional":false},{"id":"bo-luc-lac-ingredient-4","name":"Hành tây","quantity":"1 củ","category":"Rau củ","position":4,"optional":false},{"id":"bo-luc-lac-ingredient-5","name":"Xà lách","quantity":"1 cây","category":"Rau củ","position":5,"optional":false},{"id":"bo-luc-lac-ingredient-6","name":"Tỏi","quantity":"4 tép","category":"Rau củ","position":6,"optional":false},{"id":"bo-luc-lac-ingredient-7","name":"Dầu hào","quantity":"2 muỗng canh","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"bo-luc-lac-step-1","position":1,"description":"Cắt bò thành khối 2–3cm, ướp với tỏi, dầu hào, nước tương và tiêu 15 phút."},{"id":"bo-luc-lac-step-2","position":2,"description":"Cắt khoai tây thành múi, áp chảo hoặc nướng đến vàng; cắt hành tây và ớt chuông."},{"id":"bo-luc-lac-step-3","position":3,"description":"Làm chảo thật nóng, áp bò từng mẻ 1–2 phút để mặt ngoài xém mà bên trong còn mềm."},{"id":"bo-luc-lac-step-4","position":4,"description":"Xào nhanh hành và ớt, cho bò trở lại đảo 30 giây; dùng cùng khoai và xà lách."}]'::jsonb
);

select public.replace_meal_recipe(
  'ga-nuong-mat-ong',
  '[{"id":"ga-nuong-mat-ong-ingredient-1","name":"Đùi gà","quantity":"6 chiếc","category":"Thịt & Hải sản","position":1,"optional":false},{"id":"ga-nuong-mat-ong-ingredient-2","name":"Mật ong","quantity":"3 muỗng canh","category":"Gia vị & Khác","position":2,"optional":false},{"id":"ga-nuong-mat-ong-ingredient-3","name":"Tỏi","quantity":"4 tép","category":"Rau củ","position":3,"optional":false},{"id":"ga-nuong-mat-ong-ingredient-4","name":"Nước tương","quantity":"2 muỗng canh","category":"Gia vị & Khác","position":4,"optional":false},{"id":"ga-nuong-mat-ong-ingredient-5","name":"Dầu hào","quantity":"1 muỗng canh","category":"Gia vị & Khác","position":5,"optional":false},{"id":"ga-nuong-mat-ong-ingredient-6","name":"Cà rốt","quantity":"1 củ","category":"Rau củ","position":6,"optional":false},{"id":"ga-nuong-mat-ong-ingredient-7","name":"Xà lách","quantity":"1 cây","category":"Rau củ","position":7,"optional":false}]'::jsonb,
  '[{"id":"ga-nuong-mat-ong-step-1","position":1,"description":"Khứa nhẹ đùi gà; trộn mật ong, tỏi băm, nước tương, dầu hào và tiêu."},{"id":"ga-nuong-mat-ong-step-2","position":2,"description":"Ướp gà ít nhất 30 phút; làm nóng lò ở 200°C."},{"id":"ga-nuong-mat-ong-step-3","position":3,"description":"Nướng gà 25 phút, lật mặt và phết sốt ướp; nướng thêm 12–15 phút đến chín."},{"id":"ga-nuong-mat-ong-step-4","position":4,"description":"Để gà nghỉ 5 phút rồi dùng cùng salad cà rốt và xà lách."}]'::jsonb
);

select public.replace_meal_recipe(
  'tom-xao-rau-cu',
  '[{"id":"tom-xao-rau-cu-ingredient-1","name":"Tôm tươi","quantity":"450g","category":"Thịt & Hải sản","position":1,"optional":false},{"id":"tom-xao-rau-cu-ingredient-2","name":"Bông cải xanh","quantity":"250g","category":"Rau củ","position":2,"optional":false},{"id":"tom-xao-rau-cu-ingredient-3","name":"Đậu Hà Lan","quantity":"150g","category":"Rau củ","position":3,"optional":false},{"id":"tom-xao-rau-cu-ingredient-4","name":"Cà rốt","quantity":"1 củ","category":"Rau củ","position":4,"optional":false},{"id":"tom-xao-rau-cu-ingredient-5","name":"Ớt chuông đỏ","quantity":"1 quả","category":"Rau củ","position":5,"optional":false},{"id":"tom-xao-rau-cu-ingredient-6","name":"Tỏi","quantity":"3 tép","category":"Rau củ","position":6,"optional":false},{"id":"tom-xao-rau-cu-ingredient-7","name":"Dầu hào","quantity":"1.5 muỗng canh","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"tom-xao-rau-cu-step-1","position":1,"description":"Bóc vỏ, rút chỉ tôm và để ráo; cắt rau củ vừa ăn."},{"id":"tom-xao-rau-cu-step-2","position":2,"description":"Chần bông cải, cà rốt và đậu Hà Lan 1 phút, vớt ra để ráo."},{"id":"tom-xao-rau-cu-step-3","position":3,"description":"Phi tỏi, xào tôm lửa lớn đến vừa đổi màu rồi lấy ra."},{"id":"tom-xao-rau-cu-step-4","position":4,"description":"Xào rau củ 2 phút, thêm dầu hào và tôm; đảo thêm 1 phút rồi tắt bếp."}]'::jsonb
);

select public.replace_meal_recipe(
  'canh-ga-la-giang',
  '[{"id":"canh-ga-la-giang-ingredient-1","name":"Thịt gà","quantity":"600g","category":"Thịt & Hải sản","position":1,"optional":false},{"id":"canh-ga-la-giang-ingredient-2","name":"Lá giang","quantity":"1 bó","category":"Rau củ","position":2,"optional":false},{"id":"canh-ga-la-giang-ingredient-3","name":"Cà chua","quantity":"2 quả","category":"Rau củ","position":3,"optional":false},{"id":"canh-ga-la-giang-ingredient-4","name":"Hành tím","quantity":"3 củ","category":"Rau củ","position":4,"optional":false},{"id":"canh-ga-la-giang-ingredient-5","name":"Rau mùi","quantity":"1 bó nhỏ","category":"Rau củ","position":5,"optional":false},{"id":"canh-ga-la-giang-ingredient-6","name":"Nước mắm","quantity":"2 muỗng canh","category":"Gia vị & Khác","position":6,"optional":false},{"id":"canh-ga-la-giang-ingredient-7","name":"Dầu ăn","quantity":"1 muỗng canh","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"canh-ga-la-giang-step-1","position":1,"description":"Chặt gà miếng vừa ăn; vò nhẹ lá giang đã rửa sạch, bổ múi cà chua."},{"id":"canh-ga-la-giang-step-2","position":2,"description":"Phi hành tím, xào gà đến săn rồi thêm 1.2 lít nước và nấu 18 phút."},{"id":"canh-ga-la-giang-step-3","position":3,"description":"Cho cà chua và lá giang vào, nấu thêm 5 phút để vị chua hòa vào nước."},{"id":"canh-ga-la-giang-step-4","position":4,"description":"Nêm nước mắm và đường vừa vị, thêm rau mùi rồi tắt bếp."}]'::jsonb
);

select public.replace_meal_recipe(
  'thit-luon-rau-cu',
  '[{"id":"thit-luon-rau-cu-ingredient-1","name":"Thịt ba chỉ","quantity":"500g","category":"Thịt & Hải sản","position":1,"optional":false},{"id":"thit-luon-rau-cu-ingredient-2","name":"Rau củ thập cẩm","quantity":"500g","category":"Rau củ","position":2,"optional":false},{"id":"thit-luon-rau-cu-ingredient-3","name":"Gừng","quantity":"1 nhánh","category":"Rau củ","position":3,"optional":false},{"id":"thit-luon-rau-cu-ingredient-4","name":"Hành tím","quantity":"2 củ","category":"Rau củ","position":4,"optional":false},{"id":"thit-luon-rau-cu-ingredient-5","name":"Mắm nêm","quantity":"120ml","category":"Gia vị & Khác","position":5,"optional":false},{"id":"thit-luon-rau-cu-ingredient-6","name":"Dứa băm","quantity":"80g","category":"Rau củ","position":6,"optional":false},{"id":"thit-luon-rau-cu-ingredient-7","name":"Chanh","quantity":"1 quả","category":"Rau củ","position":7,"optional":false}]'::jsonb,
  '[{"id":"thit-luon-rau-cu-step-1","position":1,"description":"Rửa thịt, cho vào nồi nước cùng gừng và hành tím; luộc sôi nhẹ 22–25 phút."},{"id":"thit-luon-rau-cu-step-2","position":2,"description":"Vớt thịt ngâm nước nguội 3 phút rồi để ráo và thái lát mỏng."},{"id":"thit-luon-rau-cu-step-3","position":3,"description":"Luộc từng loại rau củ vừa chín để giữ màu và độ giòn, sau đó để ráo."},{"id":"thit-luon-rau-cu-step-4","position":4,"description":"Pha mắm nêm với dứa băm, đường và chanh; dùng cùng thịt và rau củ."}]'::jsonb
);

select public.replace_meal_recipe(
  'bun-cha',
  '[{"id":"bun-cha-ingredient-1","name":"Bún tươi","quantity":"700g","category":"Gia vị & Khác","position":1,"optional":false},{"id":"bun-cha-ingredient-2","name":"Thịt heo xay","quantity":"350g","category":"Thịt & Hải sản","position":2,"optional":false},{"id":"bun-cha-ingredient-3","name":"Thịt ba chỉ","quantity":"250g","category":"Thịt & Hải sản","position":3,"optional":false},{"id":"bun-cha-ingredient-4","name":"Đu đủ xanh","quantity":"200g","category":"Rau củ","position":4,"optional":false},{"id":"bun-cha-ingredient-5","name":"Cà rốt","quantity":"1 củ","category":"Rau củ","position":5,"optional":false},{"id":"bun-cha-ingredient-6","name":"Rau sống","quantity":"400g","category":"Rau củ","position":6,"optional":false},{"id":"bun-cha-ingredient-7","name":"Nước mắm","quantity":"120ml","category":"Gia vị & Khác","position":7,"optional":false}]'::jsonb,
  '[{"id":"bun-cha-step-1","position":1,"description":"Ướp thịt xay và ba chỉ thái mỏng với hành tím, nước mắm, đường và tiêu 30 phút."},{"id":"bun-cha-step-2","position":2,"description":"Nặn thịt xay thành miếng dẹt; nướng thịt và ba chỉ đến chín, cạnh hơi xém."},{"id":"bun-cha-step-3","position":3,"description":"Pha nước chấm ấm từ nước mắm, đường, giấm và nước; thêm đu đủ, cà rốt ngâm chua."},{"id":"bun-cha-step-4","position":4,"description":"Cho thịt nướng vào bát nước chấm, dùng cùng bún tươi và rau sống."}]'::jsonb
);
